# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegistryFindRegisteredModelRequest")

model.instance <- RegistryFindRegisteredModelRequest$new()

test_that("workspace_name", {
  # tests for the property `workspace_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`workspace_name`, "EXPECTED_RESULT")
})

test_that("predicates", {
  # tests for the property `predicates` (array[CommonKeyValueQuery])

  # uncomment below to test the property 
  #expect_equal(model.instance$`predicates`, "EXPECTED_RESULT")
})

test_that("pagination", {
  # tests for the property `pagination` (VertacommonPagination)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pagination`, "EXPECTED_RESULT")
})

test_that("ascending", {
  # tests for the property `ascending` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`ascending`, "EXPECTED_RESULT")
})

test_that("sort_key", {
  # tests for the property `sort_key` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`sort_key`, "EXPECTED_RESULT")
})

