# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegistryRegisteredModel")

model.instance <- RegistryRegisteredModel$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Unique name for the model within the workspace.

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("time_created", {
  # tests for the property `time_created` (character)
  # Timestamp recorded when this &#x60;&#x60;registered_model&#x60;&#x60; was created.

  # uncomment below to test the property 
  #expect_equal(model.instance$`time_created`, "EXPECTED_RESULT")
})

test_that("time_updated", {
  # tests for the property `time_updated` (character)
  # Timestamp recorded when metadata for this &#x60;&#x60;registered_model&#x60;&#x60; was last updated.

  # uncomment below to test the property 
  #expect_equal(model.instance$`time_updated`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Description of this &#x60;&#x60;registered_model&#x60;&#x60;.

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("labels", {
  # tests for the property `labels` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`labels`, "EXPECTED_RESULT")
})

test_that("visibility", {
  # tests for the property `visibility` (VisibilityEnumVisibility)

  # uncomment below to test the property 
  #expect_equal(model.instance$`visibility`, "EXPECTED_RESULT")
})

test_that("workspace_id", {
  # tests for the property `workspace_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`workspace_id`, "EXPECTED_RESULT")
})

test_that("workspace_service_id", {
  # tests for the property `workspace_service_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`workspace_service_id`, "EXPECTED_RESULT")
})

test_that("readme_text", {
  # tests for the property `readme_text` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`readme_text`, "EXPECTED_RESULT")
})

test_that("owner", {
  # tests for the property `owner` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`owner`, "EXPECTED_RESULT")
})

test_that("attributes", {
  # tests for the property `attributes` (array[CommonKeyValue])

  # uncomment below to test the property 
  #expect_equal(model.instance$`attributes`, "EXPECTED_RESULT")
})

test_that("custom_permission", {
  # tests for the property `custom_permission` (UacCollaboratorPermissions)

  # uncomment below to test the property 
  #expect_equal(model.instance$`custom_permission`, "EXPECTED_RESULT")
})

test_that("resource_visibility", {
  # tests for the property `resource_visibility` (UacResourceVisibility)

  # uncomment below to test the property 
  #expect_equal(model.instance$`resource_visibility`, "EXPECTED_RESULT")
})

