# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegistryRegisteredModelIdentification")

model.instance <- RegistryRegisteredModelIdentification$new()

test_that("named_id", {
  # tests for the property `named_id` (RegistryRegisteredModelNamedIdentification)

  # uncomment below to test the property 
  #expect_equal(model.instance$`named_id`, "EXPECTED_RESULT")
})

test_that("registered_model_id", {
  # tests for the property `registered_model_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`registered_model_id`, "EXPECTED_RESULT")
})

