# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegistryGetRegisteredModelCountRequestResponse")

model.instance <- RegistryGetRegisteredModelCountRequestResponse$new()

test_that("registered_model_count", {
  # tests for the property `registered_model_count` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`registered_model_count`, "EXPECTED_RESULT")
})

