# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegistryModelVersion")

model.instance <- RegistryModelVersion$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("registered_model_id", {
  # tests for the property `registered_model_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`registered_model_id`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("time_updated", {
  # tests for the property `time_updated` (character)
  # Timestamp recorded when metadata for this &#x60;&#x60;model_version&#x60;&#x60; was last updated.

  # uncomment below to test the property 
  #expect_equal(model.instance$`time_updated`, "EXPECTED_RESULT")
})

test_that("time_created", {
  # tests for the property `time_created` (character)
  # Timestamp recorded when this &#x60;&#x60;model_version&#x60;&#x60; was created.

  # uncomment below to test the property 
  #expect_equal(model.instance$`time_created`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Description of this &#x60;&#x60;model_version&#x60;&#x60;.

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("experiment_run_id", {
  # tests for the property `experiment_run_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`experiment_run_id`, "EXPECTED_RESULT")
})

test_that("labels", {
  # tests for the property `labels` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`labels`, "EXPECTED_RESULT")
})

test_that("model", {
  # tests for the property `model` (CommonArtifact)

  # uncomment below to test the property 
  #expect_equal(model.instance$`model`, "EXPECTED_RESULT")
})

test_that("environment", {
  # tests for the property `environment` (VersioningEnvironmentBlob)

  # uncomment below to test the property 
  #expect_equal(model.instance$`environment`, "EXPECTED_RESULT")
})

test_that("artifacts", {
  # tests for the property `artifacts` (array[CommonArtifact])

  # uncomment below to test the property 
  #expect_equal(model.instance$`artifacts`, "EXPECTED_RESULT")
})

test_that("archived", {
  # tests for the property `archived` (TernaryEnumTernary)

  # uncomment below to test the property 
  #expect_equal(model.instance$`archived`, "EXPECTED_RESULT")
})

test_that("readme_text", {
  # tests for the property `readme_text` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`readme_text`, "EXPECTED_RESULT")
})

test_that("apis", {
  # tests for the property `apis` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`apis`, "EXPECTED_RESULT")
})

test_that("owner", {
  # tests for the property `owner` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`owner`, "EXPECTED_RESULT")
})

test_that("attributes", {
  # tests for the property `attributes` (array[CommonKeyValue])

  # uncomment below to test the property 
  #expect_equal(model.instance$`attributes`, "EXPECTED_RESULT")
})

test_that("stage", {
  # tests for the property `stage` (StageEnumStage)

  # uncomment below to test the property 
  #expect_equal(model.instance$`stage`, "EXPECTED_RESULT")
})

test_that("lock_level", {
  # tests for the property `lock_level` (ModelVersionLockLevelEnumModelVersionLockLevel)

  # uncomment below to test the property 
  #expect_equal(model.instance$`lock_level`, "EXPECTED_RESULT")
})

