# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VertacommonPagination")

model.instance <- VertacommonPagination$new()

test_that("page_number", {
  # tests for the property `page_number` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`page_number`, "EXPECTED_RESULT")
})

test_that("page_limit", {
  # tests for the property `page_limit` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`page_limit`, "EXPECTED_RESULT")
})

