# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegistryServiceApi")

api.instance <- RegistryServiceApi$new()

test_that("RegistryServiceCommitArtifactPart", {
  # tests for RegistryServiceCommitArtifactPart
  # base path: http://localhost/v1
  # @param model.version.id character id of model version
  # @param body RegistryCommitArtifactPart 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceCommitMultipartArtifact", {
  # tests for RegistryServiceCommitMultipartArtifact
  # base path: http://localhost/v1
  # @param model.version.id character id of model version
  # @param body RegistryCommitMultipartArtifact 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceCreateModelVersion", {
  # tests for RegistryServiceCreateModelVersion
  # base path: http://localhost/v1
  # @param id.model.id.named.id.workspace.name character WorkspaceName
  # @param id.model.id.named.id.name character Model Name
  # @param body RegistryModelVersion 
  # @return [RegistrySetModelVersionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceCreateModelVersion2", {
  # tests for RegistryServiceCreateModelVersion2
  # base path: http://localhost/v1
  # @param id.model.id.registered.model.id character Model refered to by id
  # @param body RegistryModelVersion 
  # @return [RegistrySetModelVersionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceCreateRegisteredModel", {
  # tests for RegistryServiceCreateRegisteredModel
  # base path: http://localhost/v1
  # @param id.named.id.workspace.name character WorkspaceName
  # @param body RegistryRegisteredModel 
  # @return [RegistrySetRegisteredModelResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceDeleteModelVersion", {
  # tests for RegistryServiceDeleteModelVersion
  # base path: http://localhost/v1
  # @param id.model.id.named.id.workspace.name character WorkspaceName
  # @param id.model.id.named.id.name character Model Name
  # @param id.model.version.id character ModelVersion referred to by id
  # @param id.model.id.registered.model.id character Model refered to by id. (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceDeleteModelVersion2", {
  # tests for RegistryServiceDeleteModelVersion2
  # base path: http://localhost/v1
  # @param id.model.id.registered.model.id character Model refered to by id
  # @param id.model.version.id character ModelVersion referred to by id
  # @param id.model.id.named.id.name character Model Name. (optional)
  # @param id.model.id.named.id.workspace.name character WorkspaceName. (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceDeleteModelVersion3", {
  # tests for RegistryServiceDeleteModelVersion3
  # base path: http://localhost/v1
  # @param id.model.version.id character ModelVersion referred to by id
  # @param id.model.id.named.id.name character Model Name. (optional)
  # @param id.model.id.named.id.workspace.name character WorkspaceName. (optional)
  # @param id.model.id.registered.model.id character Model refered to by id. (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceDeleteRegisteredModel", {
  # tests for RegistryServiceDeleteRegisteredModel
  # base path: http://localhost/v1
  # @param id.named.id.workspace.name character WorkspaceName
  # @param id.named.id.name character Model Name
  # @param id.registered.model.id character Model refered to by id. (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceDeleteRegisteredModel2", {
  # tests for RegistryServiceDeleteRegisteredModel2
  # base path: http://localhost/v1
  # @param id.registered.model.id character Model refered to by id
  # @param id.named.id.name character Model Name. (optional)
  # @param id.named.id.workspace.name character WorkspaceName. (optional)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceFindModelVersion", {
  # tests for RegistryServiceFindModelVersion
  # base path: http://localhost/v1
  # CRUD for Model Version
  # @param id.named.id.workspace.name character WorkspaceName
  # @param id.named.id.name character Model Name
  # @param body RegistryFindModelVersionRequest 
  # @return [RegistryFindModelVersionRequestResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceFindModelVersion2", {
  # tests for RegistryServiceFindModelVersion2
  # base path: http://localhost/v1
  # CRUD for Model Version
  # @param id.registered.model.id character Model refered to by id
  # @param body RegistryFindModelVersionRequest 
  # @return [RegistryFindModelVersionRequestResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceFindModelVersion3", {
  # tests for RegistryServiceFindModelVersion3
  # base path: http://localhost/v1
  # CRUD for Model Version
  # @param id.named.id.workspace.name character WorkspaceName
  # @param body RegistryFindModelVersionRequest 
  # @return [RegistryFindModelVersionRequestResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceFindModelVersion4", {
  # tests for RegistryServiceFindModelVersion4
  # base path: http://localhost/v1
  # CRUD for Model Version
  # @param body RegistryFindModelVersionRequest 
  # @return [RegistryFindModelVersionRequestResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceFindRegisteredModel", {
  # tests for RegistryServiceFindRegisteredModel
  # base path: http://localhost/v1
  # CRUD for RegisteredModel
  # @param workspace.name character User or organization name
  # @param body RegistryFindRegisteredModelRequest 
  # @return [RegistryFindRegisteredModelRequestResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceFindRegisteredModel2", {
  # tests for RegistryServiceFindRegisteredModel2
  # base path: http://localhost/v1
  # CRUD for RegisteredModel
  # @param body RegistryFindRegisteredModelRequest 
  # @return [RegistryFindRegisteredModelRequestResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceGetCommittedArtifactParts", {
  # tests for RegistryServiceGetCommittedArtifactParts
  # base path: http://localhost/v1
  # @param model.version.id character id of model version
  # @param key character artifact key. (optional)
  # @return [RegistryGetCommittedArtifactPartsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceGetModelVersion", {
  # tests for RegistryServiceGetModelVersion
  # base path: http://localhost/v1
  # @param id.model.id.named.id.workspace.name character WorkspaceName
  # @param id.model.id.named.id.name character Model Name
  # @param id.model.version.id character ModelVersion referred to by id
  # @param id.model.id.registered.model.id character Model refered to by id. (optional)
  # @return [RegistryGetModelVersionRequestResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceGetModelVersion2", {
  # tests for RegistryServiceGetModelVersion2
  # base path: http://localhost/v1
  # @param id.model.version.id character ModelVersion referred to by id
  # @param id.model.id.named.id.name character Model Name. (optional)
  # @param id.model.id.named.id.workspace.name character WorkspaceName. (optional)
  # @param id.model.id.registered.model.id character Model refered to by id. (optional)
  # @return [RegistryGetModelVersionRequestResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceGetRegisteredModel", {
  # tests for RegistryServiceGetRegisteredModel
  # base path: http://localhost/v1
  # @param id.named.id.workspace.name character WorkspaceName
  # @param id.named.id.name character Model Name
  # @param id.registered.model.id character Model refered to by id. (optional)
  # @return [RegistryGetRegisteredModelRequestResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceGetRegisteredModel2", {
  # tests for RegistryServiceGetRegisteredModel2
  # base path: http://localhost/v1
  # @param id.registered.model.id character Model refered to by id
  # @param id.named.id.name character Model Name. (optional)
  # @param id.named.id.workspace.name character WorkspaceName. (optional)
  # @return [RegistryGetRegisteredModelRequestResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceGetRegisteredModelCount", {
  # tests for RegistryServiceGetRegisteredModelCount
  # base path: http://localhost/v1
  # @param project.id character  (optional)
  # @return [RegistryGetRegisteredModelCountRequestResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceGetUrlForArtifact", {
  # tests for RegistryServiceGetUrlForArtifact
  # base path: http://localhost/v1
  # @param model.version.id character id of model version
  # @param body RegistryGetUrlForArtifact 
  # @return [RegistryGetUrlForArtifactResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceSetLockModelVersion", {
  # tests for RegistryServiceSetLockModelVersion
  # base path: http://localhost/v1
  # @param id.model.version.id character ModelVersion referred to by id
  # @param body RegistrySetLockModelVersionRequest 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceUpdateModelVersion", {
  # tests for RegistryServiceUpdateModelVersion
  # base path: http://localhost/v1
  # @param id.model.id.named.id.workspace.name character WorkspaceName
  # @param id.model.id.named.id.name character Model Name
  # @param id.model.version.id character ModelVersion referred to by id
  # @param body RegistryModelVersion 
  # @return [RegistrySetModelVersionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceUpdateModelVersion2", {
  # tests for RegistryServiceUpdateModelVersion2
  # base path: http://localhost/v1
  # @param id.model.id.registered.model.id character Model refered to by id
  # @param id.model.version.id character ModelVersion referred to by id
  # @param body RegistryModelVersion 
  # @return [RegistrySetModelVersionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceUpdateModelVersion3", {
  # tests for RegistryServiceUpdateModelVersion3
  # base path: http://localhost/v1
  # @param id.model.id.named.id.workspace.name character WorkspaceName
  # @param id.model.id.named.id.name character Model Name
  # @param id.model.version.id character ModelVersion referred to by id
  # @param body RegistrySetModelVersion 
  # @return [RegistrySetModelVersionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceUpdateModelVersion4", {
  # tests for RegistryServiceUpdateModelVersion4
  # base path: http://localhost/v1
  # @param id.model.id.registered.model.id character Model refered to by id
  # @param id.model.version.id character ModelVersion referred to by id
  # @param body RegistrySetModelVersion 
  # @return [RegistrySetModelVersionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceUpdateModelVersion5", {
  # tests for RegistryServiceUpdateModelVersion5
  # base path: http://localhost/v1
  # @param id.model.id.named.id.workspace.name character WorkspaceName
  # @param id.model.id.named.id.name character Model Name
  # @param id.model.version.id character ModelVersion referred to by id
  # @param body RegistryModelVersion 
  # @return [RegistrySetModelVersionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceUpdateModelVersion6", {
  # tests for RegistryServiceUpdateModelVersion6
  # base path: http://localhost/v1
  # @param id.model.id.registered.model.id character Model refered to by id
  # @param id.model.version.id character ModelVersion referred to by id
  # @param body RegistryModelVersion 
  # @return [RegistrySetModelVersionResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceUpdateRegisteredModel", {
  # tests for RegistryServiceUpdateRegisteredModel
  # base path: http://localhost/v1
  # @param id.named.id.workspace.name character WorkspaceName
  # @param id.named.id.name character Model Name
  # @param body RegistryRegisteredModel 
  # @return [RegistrySetRegisteredModelResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceUpdateRegisteredModel2", {
  # tests for RegistryServiceUpdateRegisteredModel2
  # base path: http://localhost/v1
  # @param id.registered.model.id character Model refered to by id
  # @param body RegistryRegisteredModel 
  # @return [RegistrySetRegisteredModelResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceUpdateRegisteredModel3", {
  # tests for RegistryServiceUpdateRegisteredModel3
  # base path: http://localhost/v1
  # @param id.named.id.workspace.name character WorkspaceName
  # @param id.named.id.name character Model Name
  # @param body RegistrySetRegisteredModel 
  # @return [RegistrySetRegisteredModelResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceUpdateRegisteredModel4", {
  # tests for RegistryServiceUpdateRegisteredModel4
  # base path: http://localhost/v1
  # @param id.registered.model.id character Model refered to by id
  # @param body RegistrySetRegisteredModel 
  # @return [RegistrySetRegisteredModelResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceUpdateRegisteredModel5", {
  # tests for RegistryServiceUpdateRegisteredModel5
  # base path: http://localhost/v1
  # @param id.named.id.workspace.name character WorkspaceName
  # @param id.named.id.name character Model Name
  # @param body RegistryRegisteredModel 
  # @return [RegistrySetRegisteredModelResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RegistryServiceUpdateRegisteredModel6", {
  # tests for RegistryServiceUpdateRegisteredModel6
  # base path: http://localhost/v1
  # @param id.registered.model.id character Model refered to by id
  # @param body RegistryRegisteredModel 
  # @return [RegistrySetRegisteredModelResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

