# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegistryFindModelVersionRequestResponse")

model.instance <- RegistryFindModelVersionRequestResponse$new()

test_that("model_versions", {
  # tests for the property `model_versions` (array[RegistryModelVersion])

  # uncomment below to test the property 
  #expect_equal(model.instance$`model_versions`, "EXPECTED_RESULT")
})

test_that("total_records", {
  # tests for the property `total_records` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`total_records`, "EXPECTED_RESULT")
})

