# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VersioningVersionEnvironmentBlob")

model.instance <- VersioningVersionEnvironmentBlob$new()

test_that("major", {
  # tests for the property `major` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`major`, "EXPECTED_RESULT")
})

test_that("minor", {
  # tests for the property `minor` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`minor`, "EXPECTED_RESULT")
})

test_that("patch", {
  # tests for the property `patch` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`patch`, "EXPECTED_RESULT")
})

test_that("suffix", {
  # tests for the property `suffix` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`suffix`, "EXPECTED_RESULT")
})

