# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegistrySetLockModelVersionRequest")

model.instance <- RegistrySetLockModelVersionRequest$new()

test_that("id", {
  # tests for the property `id` (RegistryModelVersionIdentification)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("lock_level", {
  # tests for the property `lock_level` (ModelVersionLockLevelEnumModelVersionLockLevel)

  # uncomment below to test the property 
  #expect_equal(model.instance$`lock_level`, "EXPECTED_RESULT")
})

