# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CommonArtifactPart")

model.instance <- CommonArtifactPart$new()

test_that("part_number", {
  # tests for the property `part_number` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`part_number`, "EXPECTED_RESULT")
})

test_that("etag", {
  # tests for the property `etag` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`etag`, "EXPECTED_RESULT")
})

