# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VersioningEnvironmentBlob")

model.instance <- VersioningEnvironmentBlob$new()

test_that("python", {
  # tests for the property `python` (VersioningPythonEnvironmentBlob)

  # uncomment below to test the property 
  #expect_equal(model.instance$`python`, "EXPECTED_RESULT")
})

test_that("docker", {
  # tests for the property `docker` (VersioningDockerEnvironmentBlob)

  # uncomment below to test the property 
  #expect_equal(model.instance$`docker`, "EXPECTED_RESULT")
})

test_that("environment_variables", {
  # tests for the property `environment_variables` (array[VersioningEnvironmentVariablesBlob])

  # uncomment below to test the property 
  #expect_equal(model.instance$`environment_variables`, "EXPECTED_RESULT")
})

test_that("command_line", {
  # tests for the property `command_line` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`command_line`, "EXPECTED_RESULT")
})

