# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VersioningPythonRequirementEnvironmentBlob")

model.instance <- VersioningPythonRequirementEnvironmentBlob$new()

test_that("library", {
  # tests for the property `library` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`library`, "EXPECTED_RESULT")
})

test_that("constraint", {
  # tests for the property `constraint` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`constraint`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (VersioningVersionEnvironmentBlob)

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

