# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VersioningPythonEnvironmentBlob")

model.instance <- VersioningPythonEnvironmentBlob$new()

test_that("version", {
  # tests for the property `version` (VersioningVersionEnvironmentBlob)

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("requirements", {
  # tests for the property `requirements` (array[VersioningPythonRequirementEnvironmentBlob])

  # uncomment below to test the property 
  #expect_equal(model.instance$`requirements`, "EXPECTED_RESULT")
})

test_that("constraints", {
  # tests for the property `constraints` (array[VersioningPythonRequirementEnvironmentBlob])

  # uncomment below to test the property 
  #expect_equal(model.instance$`constraints`, "EXPECTED_RESULT")
})

