# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ProtobufFieldMask")

model.instance <- ProtobufFieldMask$new()

test_that("paths", {
  # tests for the property `paths` (array[character])
  # The set of field mask paths.

  # uncomment below to test the property 
  #expect_equal(model.instance$`paths`, "EXPECTED_RESULT")
})

