# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegistrySetModelVersion")

model.instance <- RegistrySetModelVersion$new()

test_that("id", {
  # tests for the property `id` (RegistryModelVersionIdentification)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("model_version", {
  # tests for the property `model_version` (RegistryModelVersion)

  # uncomment below to test the property 
  #expect_equal(model.instance$`model_version`, "EXPECTED_RESULT")
})

test_that("update_mask", {
  # tests for the property `update_mask` (ProtobufFieldMask)

  # uncomment below to test the property 
  #expect_equal(model.instance$`update_mask`, "EXPECTED_RESULT")
})

