# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VersioningDockerEnvironmentBlob")

model.instance <- VersioningDockerEnvironmentBlob$new()

test_that("repository", {
  # tests for the property `repository` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`repository`, "EXPECTED_RESULT")
})

test_that("tag", {
  # tests for the property `tag` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`tag`, "EXPECTED_RESULT")
})

test_that("sha", {
  # tests for the property `sha` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`sha`, "EXPECTED_RESULT")
})

