# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegistrySetModelVersionResponse")

model.instance <- RegistrySetModelVersionResponse$new()

test_that("model_version", {
  # tests for the property `model_version` (RegistryModelVersion)

  # uncomment below to test the property 
  #expect_equal(model.instance$`model_version`, "EXPECTED_RESULT")
})

