# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegistryGetCommittedArtifactPartsResponse")

model.instance <- RegistryGetCommittedArtifactPartsResponse$new()

test_that("artifact_parts", {
  # tests for the property `artifact_parts` (array[CommonArtifactPart])

  # uncomment below to test the property 
  #expect_equal(model.instance$`artifact_parts`, "EXPECTED_RESULT")
})

