# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegistryFindRegisteredModelRequestResponse")

model.instance <- RegistryFindRegisteredModelRequestResponse$new()

test_that("registered_models", {
  # tests for the property `registered_models` (array[RegistryRegisteredModel])

  # uncomment below to test the property 
  #expect_equal(model.instance$`registered_models`, "EXPECTED_RESULT")
})

test_that("total_records", {
  # tests for the property `total_records` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`total_records`, "EXPECTED_RESULT")
})

