# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegistryRegisteredModelNamedIdentification")

model.instance <- RegistryRegisteredModelNamedIdentification$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("workspace_name", {
  # tests for the property `workspace_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`workspace_name`, "EXPECTED_RESULT")
})

