# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegistrySetRegisteredModel")

model.instance <- RegistrySetRegisteredModel$new()

test_that("id", {
  # tests for the property `id` (RegistryRegisteredModelIdentification)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("registered_model", {
  # tests for the property `registered_model` (RegistryRegisteredModel)

  # uncomment below to test the property 
  #expect_equal(model.instance$`registered_model`, "EXPECTED_RESULT")
})

test_that("update_mask", {
  # tests for the property `update_mask` (ProtobufFieldMask)

  # uncomment below to test the property 
  #expect_equal(model.instance$`update_mask`, "EXPECTED_RESULT")
})

