# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegistryModelVersionIdentification")

model.instance <- RegistryModelVersionIdentification$new()

test_that("model_version_id", {
  # tests for the property `model_version_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`model_version_id`, "EXPECTED_RESULT")
})

test_that("model_id", {
  # tests for the property `model_id` (RegistryRegisteredModelIdentification)

  # uncomment below to test the property 
  #expect_equal(model.instance$`model_id`, "EXPECTED_RESULT")
})

