# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegistryGetRegisteredModelRequestResponse")

model.instance <- RegistryGetRegisteredModelRequestResponse$new()

test_that("registered_model", {
  # tests for the property `registered_model` (RegistryRegisteredModel)

  # uncomment below to test the property 
  #expect_equal(model.instance$`registered_model`, "EXPECTED_RESULT")
})

