# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CommonArtifactPart
#'
#' @description CommonArtifactPart Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field part_number  character [optional]
#'
#' @field etag  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CommonArtifactPart <- R6::R6Class(
  'CommonArtifactPart',
  public = list(
    `part_number` = NULL,
    `etag` = NULL,
    initialize = function(
        `part_number`=NULL, `etag`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`part_number`)) {
        stopifnot(is.character(`part_number`), length(`part_number`) == 1)
        self$`part_number` <- `part_number`
      }
      if (!is.null(`etag`)) {
        stopifnot(is.character(`etag`), length(`etag`) == 1)
        self$`etag` <- `etag`
      }
    },
    toJSON = function() {
      CommonArtifactPartObject <- list()
      if (!is.null(self$`part_number`)) {
        CommonArtifactPartObject[['part_number']] <-
          self$`part_number`
      }
      if (!is.null(self$`etag`)) {
        CommonArtifactPartObject[['etag']] <-
          self$`etag`
      }

      CommonArtifactPartObject
    },
    fromJSON = function(CommonArtifactPartJson) {
      CommonArtifactPartObject <- jsonlite::fromJSON(CommonArtifactPartJson)
      if (!is.null(CommonArtifactPartObject$`part_number`)) {
        self$`part_number` <- CommonArtifactPartObject$`part_number`
      }
      if (!is.null(CommonArtifactPartObject$`etag`)) {
        self$`etag` <- CommonArtifactPartObject$`etag`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`part_number`)) {
        sprintf(
        '"part_number":
          "%s"
                ',
        self$`part_number`
        )},
        if (!is.null(self$`etag`)) {
        sprintf(
        '"etag":
          "%s"
                ',
        self$`etag`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CommonArtifactPartJson) {
      CommonArtifactPartObject <- jsonlite::fromJSON(CommonArtifactPartJson)
      self$`part_number` <- CommonArtifactPartObject$`part_number`
      self$`etag` <- CommonArtifactPartObject$`etag`
      self
    }
  )
)

