# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ProtobufFieldMask
#'
#' @description ProtobufFieldMask Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field paths  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ProtobufFieldMask <- R6::R6Class(
  'ProtobufFieldMask',
  public = list(
    `paths` = NULL,
    initialize = function(
        `paths`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`paths`)) {
        stopifnot(is.vector(`paths`), length(`paths`) != 0)
        sapply(`paths`, function(x) stopifnot(is.character(x)))
        self$`paths` <- `paths`
      }
    },
    toJSON = function() {
      ProtobufFieldMaskObject <- list()
      if (!is.null(self$`paths`)) {
        ProtobufFieldMaskObject[['paths']] <-
          self$`paths`
      }

      ProtobufFieldMaskObject
    },
    fromJSON = function(ProtobufFieldMaskJson) {
      ProtobufFieldMaskObject <- jsonlite::fromJSON(ProtobufFieldMaskJson)
      if (!is.null(ProtobufFieldMaskObject$`paths`)) {
        self$`paths` <- ApiClient$new()$deserializeObj(ProtobufFieldMaskObject$`paths`, "array[character]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`paths`)) {
        sprintf(
        '"paths":
           [%s]
        ',
        paste(unlist(lapply(self$`paths`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ProtobufFieldMaskJson) {
      ProtobufFieldMaskObject <- jsonlite::fromJSON(ProtobufFieldMaskJson)
      self$`paths` <- ApiClient$new()$deserializeObj(ProtobufFieldMaskObject$`paths`, "array[character]", loadNamespace("openapi"))
      self
    }
  )
)

