# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistrySetRegisteredModelResponse
#'
#' @description RegistrySetRegisteredModelResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field registered_model  \link{RegistryRegisteredModel} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistrySetRegisteredModelResponse <- R6::R6Class(
  'RegistrySetRegisteredModelResponse',
  public = list(
    `registered_model` = NULL,
    initialize = function(
        `registered_model`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`registered_model`)) {
        stopifnot(R6::is.R6(`registered_model`))
        self$`registered_model` <- `registered_model`
      }
    },
    toJSON = function() {
      RegistrySetRegisteredModelResponseObject <- list()
      if (!is.null(self$`registered_model`)) {
        RegistrySetRegisteredModelResponseObject[['registered_model']] <-
          self$`registered_model`$toJSON()
      }

      RegistrySetRegisteredModelResponseObject
    },
    fromJSON = function(RegistrySetRegisteredModelResponseJson) {
      RegistrySetRegisteredModelResponseObject <- jsonlite::fromJSON(RegistrySetRegisteredModelResponseJson)
      if (!is.null(RegistrySetRegisteredModelResponseObject$`registered_model`)) {
        registered_modelObject <- RegistryRegisteredModel$new()
        registered_modelObject$fromJSON(jsonlite::toJSON(RegistrySetRegisteredModelResponseObject$registered_model, auto_unbox = TRUE, digits = NA))
        self$`registered_model` <- registered_modelObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`registered_model`)) {
        sprintf(
        '"registered_model":
        %s
        ',
        jsonlite::toJSON(self$`registered_model`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistrySetRegisteredModelResponseJson) {
      RegistrySetRegisteredModelResponseObject <- jsonlite::fromJSON(RegistrySetRegisteredModelResponseJson)
      self$`registered_model` <- RegistryRegisteredModel$new()$fromJSON(jsonlite::toJSON(RegistrySetRegisteredModelResponseObject$registered_model, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

