# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistryFindModelVersionRequestResponse
#'
#' @description RegistryFindModelVersionRequestResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field model_versions  list( \link{RegistryModelVersion} ) [optional]
#'
#' @field total_records  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistryFindModelVersionRequestResponse <- R6::R6Class(
  'RegistryFindModelVersionRequestResponse',
  public = list(
    `model_versions` = NULL,
    `total_records` = NULL,
    initialize = function(
        `model_versions`=NULL, `total_records`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`model_versions`)) {
        stopifnot(is.vector(`model_versions`), length(`model_versions`) != 0)
        sapply(`model_versions`, function(x) stopifnot(R6::is.R6(x)))
        self$`model_versions` <- `model_versions`
      }
      if (!is.null(`total_records`)) {
        stopifnot(is.character(`total_records`), length(`total_records`) == 1)
        self$`total_records` <- `total_records`
      }
    },
    toJSON = function() {
      RegistryFindModelVersionRequestResponseObject <- list()
      if (!is.null(self$`model_versions`)) {
        RegistryFindModelVersionRequestResponseObject[['model_versions']] <-
          lapply(self$`model_versions`, function(x) x$toJSON())
      }
      if (!is.null(self$`total_records`)) {
        RegistryFindModelVersionRequestResponseObject[['total_records']] <-
          self$`total_records`
      }

      RegistryFindModelVersionRequestResponseObject
    },
    fromJSON = function(RegistryFindModelVersionRequestResponseJson) {
      RegistryFindModelVersionRequestResponseObject <- jsonlite::fromJSON(RegistryFindModelVersionRequestResponseJson)
      if (!is.null(RegistryFindModelVersionRequestResponseObject$`model_versions`)) {
        self$`model_versions` <- ApiClient$new()$deserializeObj(RegistryFindModelVersionRequestResponseObject$`model_versions`, "array[RegistryModelVersion]", loadNamespace("openapi"))
      }
      if (!is.null(RegistryFindModelVersionRequestResponseObject$`total_records`)) {
        self$`total_records` <- RegistryFindModelVersionRequestResponseObject$`total_records`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`model_versions`)) {
        sprintf(
        '"model_versions":
        [%s]
',
        paste(sapply(self$`model_versions`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`total_records`)) {
        sprintf(
        '"total_records":
          "%s"
                ',
        self$`total_records`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistryFindModelVersionRequestResponseJson) {
      RegistryFindModelVersionRequestResponseObject <- jsonlite::fromJSON(RegistryFindModelVersionRequestResponseJson)
      self$`model_versions` <- ApiClient$new()$deserializeObj(RegistryFindModelVersionRequestResponseObject$`model_versions`, "array[RegistryModelVersion]", loadNamespace("openapi"))
      self$`total_records` <- RegistryFindModelVersionRequestResponseObject$`total_records`
      self
    }
  )
)

