# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistryGetModelVersionRequestResponse
#'
#' @description RegistryGetModelVersionRequestResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field model_version  \link{RegistryModelVersion} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistryGetModelVersionRequestResponse <- R6::R6Class(
  'RegistryGetModelVersionRequestResponse',
  public = list(
    `model_version` = NULL,
    initialize = function(
        `model_version`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`model_version`)) {
        stopifnot(R6::is.R6(`model_version`))
        self$`model_version` <- `model_version`
      }
    },
    toJSON = function() {
      RegistryGetModelVersionRequestResponseObject <- list()
      if (!is.null(self$`model_version`)) {
        RegistryGetModelVersionRequestResponseObject[['model_version']] <-
          self$`model_version`$toJSON()
      }

      RegistryGetModelVersionRequestResponseObject
    },
    fromJSON = function(RegistryGetModelVersionRequestResponseJson) {
      RegistryGetModelVersionRequestResponseObject <- jsonlite::fromJSON(RegistryGetModelVersionRequestResponseJson)
      if (!is.null(RegistryGetModelVersionRequestResponseObject$`model_version`)) {
        model_versionObject <- RegistryModelVersion$new()
        model_versionObject$fromJSON(jsonlite::toJSON(RegistryGetModelVersionRequestResponseObject$model_version, auto_unbox = TRUE, digits = NA))
        self$`model_version` <- model_versionObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`model_version`)) {
        sprintf(
        '"model_version":
        %s
        ',
        jsonlite::toJSON(self$`model_version`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistryGetModelVersionRequestResponseJson) {
      RegistryGetModelVersionRequestResponseObject <- jsonlite::fromJSON(RegistryGetModelVersionRequestResponseJson)
      self$`model_version` <- RegistryModelVersion$new()$fromJSON(jsonlite::toJSON(RegistryGetModelVersionRequestResponseObject$model_version, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

