# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistryRegisteredModelIdentification
#'
#' @description RegistryRegisteredModelIdentification Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field named_id  \link{RegistryRegisteredModelNamedIdentification} [optional]
#'
#' @field registered_model_id Model refered to by id character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistryRegisteredModelIdentification <- R6::R6Class(
  'RegistryRegisteredModelIdentification',
  public = list(
    `named_id` = NULL,
    `registered_model_id` = NULL,
    initialize = function(
        `named_id`=NULL, `registered_model_id`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`named_id`)) {
        stopifnot(R6::is.R6(`named_id`))
        self$`named_id` <- `named_id`
      }
      if (!is.null(`registered_model_id`)) {
        stopifnot(is.character(`registered_model_id`), length(`registered_model_id`) == 1)
        self$`registered_model_id` <- `registered_model_id`
      }
    },
    toJSON = function() {
      RegistryRegisteredModelIdentificationObject <- list()
      if (!is.null(self$`named_id`)) {
        RegistryRegisteredModelIdentificationObject[['named_id']] <-
          self$`named_id`$toJSON()
      }
      if (!is.null(self$`registered_model_id`)) {
        RegistryRegisteredModelIdentificationObject[['registered_model_id']] <-
          self$`registered_model_id`
      }

      RegistryRegisteredModelIdentificationObject
    },
    fromJSON = function(RegistryRegisteredModelIdentificationJson) {
      RegistryRegisteredModelIdentificationObject <- jsonlite::fromJSON(RegistryRegisteredModelIdentificationJson)
      if (!is.null(RegistryRegisteredModelIdentificationObject$`named_id`)) {
        named_idObject <- RegistryRegisteredModelNamedIdentification$new()
        named_idObject$fromJSON(jsonlite::toJSON(RegistryRegisteredModelIdentificationObject$named_id, auto_unbox = TRUE, digits = NA))
        self$`named_id` <- named_idObject
      }
      if (!is.null(RegistryRegisteredModelIdentificationObject$`registered_model_id`)) {
        self$`registered_model_id` <- RegistryRegisteredModelIdentificationObject$`registered_model_id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`named_id`)) {
        sprintf(
        '"named_id":
        %s
        ',
        jsonlite::toJSON(self$`named_id`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`registered_model_id`)) {
        sprintf(
        '"registered_model_id":
          "%s"
                ',
        self$`registered_model_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistryRegisteredModelIdentificationJson) {
      RegistryRegisteredModelIdentificationObject <- jsonlite::fromJSON(RegistryRegisteredModelIdentificationJson)
      self$`named_id` <- RegistryRegisteredModelNamedIdentification$new()$fromJSON(jsonlite::toJSON(RegistryRegisteredModelIdentificationObject$named_id, auto_unbox = TRUE, digits = NA))
      self$`registered_model_id` <- RegistryRegisteredModelIdentificationObject$`registered_model_id`
      self
    }
  )
)

