# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistryGetUrlForArtifact
#'
#' @description RegistryGetUrlForArtifact Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field model_version_id id of model version character [optional]
#'
#' @field key artifact key character [optional]
#'
#' @field method GET or PUT character [optional]
#'
#' @field artifact_type  \link{ArtifactTypeEnumArtifactType} [optional]
#'
#' @field part_number 0 if the url is not required to be multi part character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistryGetUrlForArtifact <- R6::R6Class(
  'RegistryGetUrlForArtifact',
  public = list(
    `model_version_id` = NULL,
    `key` = NULL,
    `method` = NULL,
    `artifact_type` = NULL,
    `part_number` = NULL,
    initialize = function(
        `model_version_id`=NULL, `key`=NULL, `method`=NULL, `artifact_type`=NULL, `part_number`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`model_version_id`)) {
        stopifnot(is.character(`model_version_id`), length(`model_version_id`) == 1)
        self$`model_version_id` <- `model_version_id`
      }
      if (!is.null(`key`)) {
        stopifnot(is.character(`key`), length(`key`) == 1)
        self$`key` <- `key`
      }
      if (!is.null(`method`)) {
        stopifnot(is.character(`method`), length(`method`) == 1)
        self$`method` <- `method`
      }
      if (!is.null(`artifact_type`)) {
        stopifnot(R6::is.R6(`artifact_type`))
        self$`artifact_type` <- `artifact_type`
      }
      if (!is.null(`part_number`)) {
        stopifnot(is.character(`part_number`), length(`part_number`) == 1)
        self$`part_number` <- `part_number`
      }
    },
    toJSON = function() {
      RegistryGetUrlForArtifactObject <- list()
      if (!is.null(self$`model_version_id`)) {
        RegistryGetUrlForArtifactObject[['model_version_id']] <-
          self$`model_version_id`
      }
      if (!is.null(self$`key`)) {
        RegistryGetUrlForArtifactObject[['key']] <-
          self$`key`
      }
      if (!is.null(self$`method`)) {
        RegistryGetUrlForArtifactObject[['method']] <-
          self$`method`
      }
      if (!is.null(self$`artifact_type`)) {
        RegistryGetUrlForArtifactObject[['artifact_type']] <-
          self$`artifact_type`$toJSON()
      }
      if (!is.null(self$`part_number`)) {
        RegistryGetUrlForArtifactObject[['part_number']] <-
          self$`part_number`
      }

      RegistryGetUrlForArtifactObject
    },
    fromJSON = function(RegistryGetUrlForArtifactJson) {
      RegistryGetUrlForArtifactObject <- jsonlite::fromJSON(RegistryGetUrlForArtifactJson)
      if (!is.null(RegistryGetUrlForArtifactObject$`model_version_id`)) {
        self$`model_version_id` <- RegistryGetUrlForArtifactObject$`model_version_id`
      }
      if (!is.null(RegistryGetUrlForArtifactObject$`key`)) {
        self$`key` <- RegistryGetUrlForArtifactObject$`key`
      }
      if (!is.null(RegistryGetUrlForArtifactObject$`method`)) {
        self$`method` <- RegistryGetUrlForArtifactObject$`method`
      }
      if (!is.null(RegistryGetUrlForArtifactObject$`artifact_type`)) {
        artifact_typeObject <- ArtifactTypeEnumArtifactType$new()
        artifact_typeObject$fromJSON(jsonlite::toJSON(RegistryGetUrlForArtifactObject$artifact_type, auto_unbox = TRUE, digits = NA))
        self$`artifact_type` <- artifact_typeObject
      }
      if (!is.null(RegistryGetUrlForArtifactObject$`part_number`)) {
        self$`part_number` <- RegistryGetUrlForArtifactObject$`part_number`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`model_version_id`)) {
        sprintf(
        '"model_version_id":
          "%s"
                ',
        self$`model_version_id`
        )},
        if (!is.null(self$`key`)) {
        sprintf(
        '"key":
          "%s"
                ',
        self$`key`
        )},
        if (!is.null(self$`method`)) {
        sprintf(
        '"method":
          "%s"
                ',
        self$`method`
        )},
        if (!is.null(self$`artifact_type`)) {
        sprintf(
        '"artifact_type":
        %s
        ',
        jsonlite::toJSON(self$`artifact_type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`part_number`)) {
        sprintf(
        '"part_number":
          "%s"
                ',
        self$`part_number`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistryGetUrlForArtifactJson) {
      RegistryGetUrlForArtifactObject <- jsonlite::fromJSON(RegistryGetUrlForArtifactJson)
      self$`model_version_id` <- RegistryGetUrlForArtifactObject$`model_version_id`
      self$`key` <- RegistryGetUrlForArtifactObject$`key`
      self$`method` <- RegistryGetUrlForArtifactObject$`method`
      self$`artifact_type` <- ArtifactTypeEnumArtifactType$new()$fromJSON(jsonlite::toJSON(RegistryGetUrlForArtifactObject$artifact_type, auto_unbox = TRUE, digits = NA))
      self$`part_number` <- RegistryGetUrlForArtifactObject$`part_number`
      self
    }
  )
)

