# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistryRegisteredModelNamedIdentification
#'
#' @description RegistryRegisteredModelNamedIdentification Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name Model Name character [optional]
#'
#' @field workspace_name WorkspaceName character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistryRegisteredModelNamedIdentification <- R6::R6Class(
  'RegistryRegisteredModelNamedIdentification',
  public = list(
    `name` = NULL,
    `workspace_name` = NULL,
    initialize = function(
        `name`=NULL, `workspace_name`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`workspace_name`)) {
        stopifnot(is.character(`workspace_name`), length(`workspace_name`) == 1)
        self$`workspace_name` <- `workspace_name`
      }
    },
    toJSON = function() {
      RegistryRegisteredModelNamedIdentificationObject <- list()
      if (!is.null(self$`name`)) {
        RegistryRegisteredModelNamedIdentificationObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`workspace_name`)) {
        RegistryRegisteredModelNamedIdentificationObject[['workspace_name']] <-
          self$`workspace_name`
      }

      RegistryRegisteredModelNamedIdentificationObject
    },
    fromJSON = function(RegistryRegisteredModelNamedIdentificationJson) {
      RegistryRegisteredModelNamedIdentificationObject <- jsonlite::fromJSON(RegistryRegisteredModelNamedIdentificationJson)
      if (!is.null(RegistryRegisteredModelNamedIdentificationObject$`name`)) {
        self$`name` <- RegistryRegisteredModelNamedIdentificationObject$`name`
      }
      if (!is.null(RegistryRegisteredModelNamedIdentificationObject$`workspace_name`)) {
        self$`workspace_name` <- RegistryRegisteredModelNamedIdentificationObject$`workspace_name`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`workspace_name`)) {
        sprintf(
        '"workspace_name":
          "%s"
                ',
        self$`workspace_name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistryRegisteredModelNamedIdentificationJson) {
      RegistryRegisteredModelNamedIdentificationObject <- jsonlite::fromJSON(RegistryRegisteredModelNamedIdentificationJson)
      self$`name` <- RegistryRegisteredModelNamedIdentificationObject$`name`
      self$`workspace_name` <- RegistryRegisteredModelNamedIdentificationObject$`workspace_name`
      self
    }
  )
)

