# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistrySetLockModelVersionRequest
#'
#' @description RegistrySetLockModelVersionRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  \link{RegistryModelVersionIdentification} [optional]
#'
#' @field lock_level  \link{ModelVersionLockLevelEnumModelVersionLockLevel} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistrySetLockModelVersionRequest <- R6::R6Class(
  'RegistrySetLockModelVersionRequest',
  public = list(
    `id` = NULL,
    `lock_level` = NULL,
    initialize = function(
        `id`=NULL, `lock_level`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(R6::is.R6(`id`))
        self$`id` <- `id`
      }
      if (!is.null(`lock_level`)) {
        stopifnot(R6::is.R6(`lock_level`))
        self$`lock_level` <- `lock_level`
      }
    },
    toJSON = function() {
      RegistrySetLockModelVersionRequestObject <- list()
      if (!is.null(self$`id`)) {
        RegistrySetLockModelVersionRequestObject[['id']] <-
          self$`id`$toJSON()
      }
      if (!is.null(self$`lock_level`)) {
        RegistrySetLockModelVersionRequestObject[['lock_level']] <-
          self$`lock_level`$toJSON()
      }

      RegistrySetLockModelVersionRequestObject
    },
    fromJSON = function(RegistrySetLockModelVersionRequestJson) {
      RegistrySetLockModelVersionRequestObject <- jsonlite::fromJSON(RegistrySetLockModelVersionRequestJson)
      if (!is.null(RegistrySetLockModelVersionRequestObject$`id`)) {
        idObject <- RegistryModelVersionIdentification$new()
        idObject$fromJSON(jsonlite::toJSON(RegistrySetLockModelVersionRequestObject$id, auto_unbox = TRUE, digits = NA))
        self$`id` <- idObject
      }
      if (!is.null(RegistrySetLockModelVersionRequestObject$`lock_level`)) {
        lock_levelObject <- ModelVersionLockLevelEnumModelVersionLockLevel$new()
        lock_levelObject$fromJSON(jsonlite::toJSON(RegistrySetLockModelVersionRequestObject$lock_level, auto_unbox = TRUE, digits = NA))
        self$`lock_level` <- lock_levelObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
        %s
        ',
        jsonlite::toJSON(self$`id`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`lock_level`)) {
        sprintf(
        '"lock_level":
        %s
        ',
        jsonlite::toJSON(self$`lock_level`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistrySetLockModelVersionRequestJson) {
      RegistrySetLockModelVersionRequestObject <- jsonlite::fromJSON(RegistrySetLockModelVersionRequestJson)
      self$`id` <- RegistryModelVersionIdentification$new()$fromJSON(jsonlite::toJSON(RegistrySetLockModelVersionRequestObject$id, auto_unbox = TRUE, digits = NA))
      self$`lock_level` <- ModelVersionLockLevelEnumModelVersionLockLevel$new()$fromJSON(jsonlite::toJSON(RegistrySetLockModelVersionRequestObject$lock_level, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

