# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistryCommitArtifactPart
#'
#' @description RegistryCommitArtifactPart Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field model_version_id id of model version character [optional]
#'
#' @field key artifact key character [optional]
#'
#' @field artifact_part  \link{CommonArtifactPart} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistryCommitArtifactPart <- R6::R6Class(
  'RegistryCommitArtifactPart',
  public = list(
    `model_version_id` = NULL,
    `key` = NULL,
    `artifact_part` = NULL,
    initialize = function(
        `model_version_id`=NULL, `key`=NULL, `artifact_part`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`model_version_id`)) {
        stopifnot(is.character(`model_version_id`), length(`model_version_id`) == 1)
        self$`model_version_id` <- `model_version_id`
      }
      if (!is.null(`key`)) {
        stopifnot(is.character(`key`), length(`key`) == 1)
        self$`key` <- `key`
      }
      if (!is.null(`artifact_part`)) {
        stopifnot(R6::is.R6(`artifact_part`))
        self$`artifact_part` <- `artifact_part`
      }
    },
    toJSON = function() {
      RegistryCommitArtifactPartObject <- list()
      if (!is.null(self$`model_version_id`)) {
        RegistryCommitArtifactPartObject[['model_version_id']] <-
          self$`model_version_id`
      }
      if (!is.null(self$`key`)) {
        RegistryCommitArtifactPartObject[['key']] <-
          self$`key`
      }
      if (!is.null(self$`artifact_part`)) {
        RegistryCommitArtifactPartObject[['artifact_part']] <-
          self$`artifact_part`$toJSON()
      }

      RegistryCommitArtifactPartObject
    },
    fromJSON = function(RegistryCommitArtifactPartJson) {
      RegistryCommitArtifactPartObject <- jsonlite::fromJSON(RegistryCommitArtifactPartJson)
      if (!is.null(RegistryCommitArtifactPartObject$`model_version_id`)) {
        self$`model_version_id` <- RegistryCommitArtifactPartObject$`model_version_id`
      }
      if (!is.null(RegistryCommitArtifactPartObject$`key`)) {
        self$`key` <- RegistryCommitArtifactPartObject$`key`
      }
      if (!is.null(RegistryCommitArtifactPartObject$`artifact_part`)) {
        artifact_partObject <- CommonArtifactPart$new()
        artifact_partObject$fromJSON(jsonlite::toJSON(RegistryCommitArtifactPartObject$artifact_part, auto_unbox = TRUE, digits = NA))
        self$`artifact_part` <- artifact_partObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`model_version_id`)) {
        sprintf(
        '"model_version_id":
          "%s"
                ',
        self$`model_version_id`
        )},
        if (!is.null(self$`key`)) {
        sprintf(
        '"key":
          "%s"
                ',
        self$`key`
        )},
        if (!is.null(self$`artifact_part`)) {
        sprintf(
        '"artifact_part":
        %s
        ',
        jsonlite::toJSON(self$`artifact_part`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistryCommitArtifactPartJson) {
      RegistryCommitArtifactPartObject <- jsonlite::fromJSON(RegistryCommitArtifactPartJson)
      self$`model_version_id` <- RegistryCommitArtifactPartObject$`model_version_id`
      self$`key` <- RegistryCommitArtifactPartObject$`key`
      self$`artifact_part` <- CommonArtifactPart$new()$fromJSON(jsonlite::toJSON(RegistryCommitArtifactPartObject$artifact_part, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

