# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistrySetRegisteredModel
#'
#' @description RegistrySetRegisteredModel Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  \link{RegistryRegisteredModelIdentification} [optional]
#'
#' @field registered_model  \link{RegistryRegisteredModel} [optional]
#'
#' @field update_mask  \link{ProtobufFieldMask} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistrySetRegisteredModel <- R6::R6Class(
  'RegistrySetRegisteredModel',
  public = list(
    `id` = NULL,
    `registered_model` = NULL,
    `update_mask` = NULL,
    initialize = function(
        `id`=NULL, `registered_model`=NULL, `update_mask`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(R6::is.R6(`id`))
        self$`id` <- `id`
      }
      if (!is.null(`registered_model`)) {
        stopifnot(R6::is.R6(`registered_model`))
        self$`registered_model` <- `registered_model`
      }
      if (!is.null(`update_mask`)) {
        stopifnot(R6::is.R6(`update_mask`))
        self$`update_mask` <- `update_mask`
      }
    },
    toJSON = function() {
      RegistrySetRegisteredModelObject <- list()
      if (!is.null(self$`id`)) {
        RegistrySetRegisteredModelObject[['id']] <-
          self$`id`$toJSON()
      }
      if (!is.null(self$`registered_model`)) {
        RegistrySetRegisteredModelObject[['registered_model']] <-
          self$`registered_model`$toJSON()
      }
      if (!is.null(self$`update_mask`)) {
        RegistrySetRegisteredModelObject[['update_mask']] <-
          self$`update_mask`$toJSON()
      }

      RegistrySetRegisteredModelObject
    },
    fromJSON = function(RegistrySetRegisteredModelJson) {
      RegistrySetRegisteredModelObject <- jsonlite::fromJSON(RegistrySetRegisteredModelJson)
      if (!is.null(RegistrySetRegisteredModelObject$`id`)) {
        idObject <- RegistryRegisteredModelIdentification$new()
        idObject$fromJSON(jsonlite::toJSON(RegistrySetRegisteredModelObject$id, auto_unbox = TRUE, digits = NA))
        self$`id` <- idObject
      }
      if (!is.null(RegistrySetRegisteredModelObject$`registered_model`)) {
        registered_modelObject <- RegistryRegisteredModel$new()
        registered_modelObject$fromJSON(jsonlite::toJSON(RegistrySetRegisteredModelObject$registered_model, auto_unbox = TRUE, digits = NA))
        self$`registered_model` <- registered_modelObject
      }
      if (!is.null(RegistrySetRegisteredModelObject$`update_mask`)) {
        update_maskObject <- ProtobufFieldMask$new()
        update_maskObject$fromJSON(jsonlite::toJSON(RegistrySetRegisteredModelObject$update_mask, auto_unbox = TRUE, digits = NA))
        self$`update_mask` <- update_maskObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
        %s
        ',
        jsonlite::toJSON(self$`id`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`registered_model`)) {
        sprintf(
        '"registered_model":
        %s
        ',
        jsonlite::toJSON(self$`registered_model`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`update_mask`)) {
        sprintf(
        '"update_mask":
        %s
        ',
        jsonlite::toJSON(self$`update_mask`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistrySetRegisteredModelJson) {
      RegistrySetRegisteredModelObject <- jsonlite::fromJSON(RegistrySetRegisteredModelJson)
      self$`id` <- RegistryRegisteredModelIdentification$new()$fromJSON(jsonlite::toJSON(RegistrySetRegisteredModelObject$id, auto_unbox = TRUE, digits = NA))
      self$`registered_model` <- RegistryRegisteredModel$new()$fromJSON(jsonlite::toJSON(RegistrySetRegisteredModelObject$registered_model, auto_unbox = TRUE, digits = NA))
      self$`update_mask` <- ProtobufFieldMask$new()$fromJSON(jsonlite::toJSON(RegistrySetRegisteredModelObject$update_mask, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

