# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
#
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistryRegisteredModel
#'
#' @description RegistryRegisteredModel Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id internal id character [optional]
#'
#' @field name  character [optional]
#'
#' @field time_created  character [optional]
#'
#' @field time_updated  character [optional]
#'
#' @field description  character [optional]
#'
#' @field labels Labels added to the registered models list( character ) [optional]
#'
#' @field visibility  \link{VisibilityEnumVisibility} [optional]
#'
#' @field workspace_id id of the workspace this belongs to
#' not storing workspace_type uac should support https://github.com/VertaAI/protos-all/pull/19/files character [optional]
#'
#' @field workspace_service_id  character [optional]
#'
#' @field readme_text readme character [optional]
#'
#' @field owner owner&#39;s verta_id character [optional]
#'
#' @field attributes Other attributes list( \link{CommonKeyValue} ) [optional]
#'
#' @field custom_permission  \link{UacCollaboratorPermissions} [optional]
#'
#' @field resource_visibility  \link{UacResourceVisibility} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistryRegisteredModel <- R6::R6Class(
  'RegistryRegisteredModel',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `time_created` = NULL,
    `time_updated` = NULL,
    `description` = NULL,
    `labels` = NULL,
    `visibility` = NULL,
    `workspace_id` = NULL,
    `workspace_service_id` = NULL,
    `readme_text` = NULL,
    `owner` = NULL,
    `attributes` = NULL,
    `custom_permission` = NULL,
    `resource_visibility` = NULL,
    initialize = function(
        `id`=NULL, `name`=NULL, `time_created`=NULL, `time_updated`=NULL, `description`=NULL, `labels`=NULL, `visibility`=NULL, `workspace_id`=NULL, `workspace_service_id`=NULL, `readme_text`=NULL, `owner`=NULL, `attributes`=NULL, `custom_permission`=NULL, `resource_visibility`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`time_created`)) {
        stopifnot(is.character(`time_created`), length(`time_created`) == 1)
        self$`time_created` <- `time_created`
      }
      if (!is.null(`time_updated`)) {
        stopifnot(is.character(`time_updated`), length(`time_updated`) == 1)
        self$`time_updated` <- `time_updated`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`labels`)) {
        stopifnot(is.vector(`labels`), length(`labels`) != 0)
        sapply(`labels`, function(x) stopifnot(is.character(x)))
        self$`labels` <- `labels`
      }
      if (!is.null(`visibility`)) {
        stopifnot(R6::is.R6(`visibility`))
        self$`visibility` <- `visibility`
      }
      if (!is.null(`workspace_id`)) {
        stopifnot(is.character(`workspace_id`), length(`workspace_id`) == 1)
        self$`workspace_id` <- `workspace_id`
      }
      if (!is.null(`workspace_service_id`)) {
        stopifnot(is.character(`workspace_service_id`), length(`workspace_service_id`) == 1)
        self$`workspace_service_id` <- `workspace_service_id`
      }
      if (!is.null(`readme_text`)) {
        stopifnot(is.character(`readme_text`), length(`readme_text`) == 1)
        self$`readme_text` <- `readme_text`
      }
      if (!is.null(`owner`)) {
        stopifnot(is.character(`owner`), length(`owner`) == 1)
        self$`owner` <- `owner`
      }
      if (!is.null(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(R6::is.R6(x)))
        self$`attributes` <- `attributes`
      }
      if (!is.null(`custom_permission`)) {
        stopifnot(R6::is.R6(`custom_permission`))
        self$`custom_permission` <- `custom_permission`
      }
      if (!is.null(`resource_visibility`)) {
        stopifnot(R6::is.R6(`resource_visibility`))
        self$`resource_visibility` <- `resource_visibility`
      }
    },
    toJSON = function() {
      RegistryRegisteredModelObject <- list()
      if (!is.null(self$`id`)) {
        RegistryRegisteredModelObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`name`)) {
        RegistryRegisteredModelObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`time_created`)) {
        RegistryRegisteredModelObject[['time_created']] <-
          self$`time_created`
      }
      if (!is.null(self$`time_updated`)) {
        RegistryRegisteredModelObject[['time_updated']] <-
          self$`time_updated`
      }
      if (!is.null(self$`description`)) {
        RegistryRegisteredModelObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`labels`)) {
        RegistryRegisteredModelObject[['labels']] <-
          self$`labels`
      }
      if (!is.null(self$`visibility`)) {
        RegistryRegisteredModelObject[['visibility']] <-
          self$`visibility`$toJSON()
      }
      if (!is.null(self$`workspace_id`)) {
        RegistryRegisteredModelObject[['workspace_id']] <-
          self$`workspace_id`
      }
      if (!is.null(self$`workspace_service_id`)) {
        RegistryRegisteredModelObject[['workspace_service_id']] <-
          self$`workspace_service_id`
      }
      if (!is.null(self$`readme_text`)) {
        RegistryRegisteredModelObject[['readme_text']] <-
          self$`readme_text`
      }
      if (!is.null(self$`owner`)) {
        RegistryRegisteredModelObject[['owner']] <-
          self$`owner`
      }
      if (!is.null(self$`attributes`)) {
        RegistryRegisteredModelObject[['attributes']] <-
          lapply(self$`attributes`, function(x) x$toJSON())
      }
      if (!is.null(self$`custom_permission`)) {
        RegistryRegisteredModelObject[['custom_permission']] <-
          self$`custom_permission`$toJSON()
      }
      if (!is.null(self$`resource_visibility`)) {
        RegistryRegisteredModelObject[['resource_visibility']] <-
          self$`resource_visibility`$toJSON()
      }

      RegistryRegisteredModelObject
    },
    fromJSON = function(RegistryRegisteredModelJson) {
      RegistryRegisteredModelObject <- jsonlite::fromJSON(RegistryRegisteredModelJson)
      if (!is.null(RegistryRegisteredModelObject$`id`)) {
        self$`id` <- RegistryRegisteredModelObject$`id`
      }
      if (!is.null(RegistryRegisteredModelObject$`name`)) {
        self$`name` <- RegistryRegisteredModelObject$`name`
      }
      if (!is.null(RegistryRegisteredModelObject$`time_created`)) {
        self$`time_created` <- RegistryRegisteredModelObject$`time_created`
      }
      if (!is.null(RegistryRegisteredModelObject$`time_updated`)) {
        self$`time_updated` <- RegistryRegisteredModelObject$`time_updated`
      }
      if (!is.null(RegistryRegisteredModelObject$`description`)) {
        self$`description` <- RegistryRegisteredModelObject$`description`
      }
      if (!is.null(RegistryRegisteredModelObject$`labels`)) {
        self$`labels` <- ApiClient$new()$deserializeObj(RegistryRegisteredModelObject$`labels`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(RegistryRegisteredModelObject$`visibility`)) {
        visibilityObject <- VisibilityEnumVisibility$new()
        visibilityObject$fromJSON(jsonlite::toJSON(RegistryRegisteredModelObject$visibility, auto_unbox = TRUE, digits = NA))
        self$`visibility` <- visibilityObject
      }
      if (!is.null(RegistryRegisteredModelObject$`workspace_id`)) {
        self$`workspace_id` <- RegistryRegisteredModelObject$`workspace_id`
      }
      if (!is.null(RegistryRegisteredModelObject$`workspace_service_id`)) {
        self$`workspace_service_id` <- RegistryRegisteredModelObject$`workspace_service_id`
      }
      if (!is.null(RegistryRegisteredModelObject$`readme_text`)) {
        self$`readme_text` <- RegistryRegisteredModelObject$`readme_text`
      }
      if (!is.null(RegistryRegisteredModelObject$`owner`)) {
        self$`owner` <- RegistryRegisteredModelObject$`owner`
      }
      if (!is.null(RegistryRegisteredModelObject$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(RegistryRegisteredModelObject$`attributes`, "array[CommonKeyValue]", loadNamespace("openapi"))
      }
      if (!is.null(RegistryRegisteredModelObject$`custom_permission`)) {
        custom_permissionObject <- UacCollaboratorPermissions$new()
        custom_permissionObject$fromJSON(jsonlite::toJSON(RegistryRegisteredModelObject$custom_permission, auto_unbox = TRUE, digits = NA))
        self$`custom_permission` <- custom_permissionObject
      }
      if (!is.null(RegistryRegisteredModelObject$`resource_visibility`)) {
        resource_visibilityObject <- UacResourceVisibility$new()
        resource_visibilityObject$fromJSON(jsonlite::toJSON(RegistryRegisteredModelObject$resource_visibility, auto_unbox = TRUE, digits = NA))
        self$`resource_visibility` <- resource_visibilityObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`time_created`)) {
        sprintf(
        '"time_created":
          "%s"
                ',
        self$`time_created`
        )},
        if (!is.null(self$`time_updated`)) {
        sprintf(
        '"time_updated":
          "%s"
                ',
        self$`time_updated`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`labels`)) {
        sprintf(
        '"labels":
           [%s]
        ',
        paste(unlist(lapply(self$`labels`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`visibility`)) {
        sprintf(
        '"visibility":
        %s
        ',
        jsonlite::toJSON(self$`visibility`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`workspace_id`)) {
        sprintf(
        '"workspace_id":
          "%s"
                ',
        self$`workspace_id`
        )},
        if (!is.null(self$`workspace_service_id`)) {
        sprintf(
        '"workspace_service_id":
          "%s"
                ',
        self$`workspace_service_id`
        )},
        if (!is.null(self$`readme_text`)) {
        sprintf(
        '"readme_text":
          "%s"
                ',
        self$`readme_text`
        )},
        if (!is.null(self$`owner`)) {
        sprintf(
        '"owner":
          "%s"
                ',
        self$`owner`
        )},
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
        [%s]
',
        paste(sapply(self$`attributes`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`custom_permission`)) {
        sprintf(
        '"custom_permission":
        %s
        ',
        jsonlite::toJSON(self$`custom_permission`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`resource_visibility`)) {
        sprintf(
        '"resource_visibility":
        %s
        ',
        jsonlite::toJSON(self$`resource_visibility`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistryRegisteredModelJson) {
      RegistryRegisteredModelObject <- jsonlite::fromJSON(RegistryRegisteredModelJson)
      self$`id` <- RegistryRegisteredModelObject$`id`
      self$`name` <- RegistryRegisteredModelObject$`name`
      self$`time_created` <- RegistryRegisteredModelObject$`time_created`
      self$`time_updated` <- RegistryRegisteredModelObject$`time_updated`
      self$`description` <- RegistryRegisteredModelObject$`description`
      self$`labels` <- ApiClient$new()$deserializeObj(RegistryRegisteredModelObject$`labels`, "array[character]", loadNamespace("openapi"))
      self$`visibility` <- VisibilityEnumVisibility$new()$fromJSON(jsonlite::toJSON(RegistryRegisteredModelObject$visibility, auto_unbox = TRUE, digits = NA))
      self$`workspace_id` <- RegistryRegisteredModelObject$`workspace_id`
      self$`workspace_service_id` <- RegistryRegisteredModelObject$`workspace_service_id`
      self$`readme_text` <- RegistryRegisteredModelObject$`readme_text`
      self$`owner` <- RegistryRegisteredModelObject$`owner`
      self$`attributes` <- ApiClient$new()$deserializeObj(RegistryRegisteredModelObject$`attributes`, "array[CommonKeyValue]", loadNamespace("openapi"))
      self$`custom_permission` <- UacCollaboratorPermissions$new()$fromJSON(jsonlite::toJSON(RegistryRegisteredModelObject$custom_permission, auto_unbox = TRUE, digits = NA))
      self$`resource_visibility` <- UacResourceVisibility$new()$fromJSON(jsonlite::toJSON(RegistryRegisteredModelObject$resource_visibility, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

