# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
#
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistryFindRegisteredModelRequest
#'
#' @description RegistryFindRegisteredModelRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field workspace_name User or organization name character [optional]
#'
#' @field predicates Filtering supported on
#' 1. name
#' 2. labels
#' 3. description list( \link{CommonKeyValueQuery} ) [optional]
#'
#' @field pagination  \link{VertacommonPagination} [optional]
#'
#' @field ascending  character [optional]
#'
#' @field sort_key  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistryFindRegisteredModelRequest <- R6::R6Class(
  'RegistryFindRegisteredModelRequest',
  public = list(
    `workspace_name` = NULL,
    `predicates` = NULL,
    `pagination` = NULL,
    `ascending` = NULL,
    `sort_key` = NULL,
    initialize = function(
        `workspace_name`=NULL, `predicates`=NULL, `pagination`=NULL, `ascending`=NULL, `sort_key`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`workspace_name`)) {
        stopifnot(is.character(`workspace_name`), length(`workspace_name`) == 1)
        self$`workspace_name` <- `workspace_name`
      }
      if (!is.null(`predicates`)) {
        stopifnot(is.vector(`predicates`), length(`predicates`) != 0)
        sapply(`predicates`, function(x) stopifnot(R6::is.R6(x)))
        self$`predicates` <- `predicates`
      }
      if (!is.null(`pagination`)) {
        stopifnot(R6::is.R6(`pagination`))
        self$`pagination` <- `pagination`
      }
      if (!is.null(`ascending`)) {
        self$`ascending` <- `ascending`
      }
      if (!is.null(`sort_key`)) {
        stopifnot(is.character(`sort_key`), length(`sort_key`) == 1)
        self$`sort_key` <- `sort_key`
      }
    },
    toJSON = function() {
      RegistryFindRegisteredModelRequestObject <- list()
      if (!is.null(self$`workspace_name`)) {
        RegistryFindRegisteredModelRequestObject[['workspace_name']] <-
          self$`workspace_name`
      }
      if (!is.null(self$`predicates`)) {
        RegistryFindRegisteredModelRequestObject[['predicates']] <-
          lapply(self$`predicates`, function(x) x$toJSON())
      }
      if (!is.null(self$`pagination`)) {
        RegistryFindRegisteredModelRequestObject[['pagination']] <-
          self$`pagination`$toJSON()
      }
      if (!is.null(self$`ascending`)) {
        RegistryFindRegisteredModelRequestObject[['ascending']] <-
          self$`ascending`
      }
      if (!is.null(self$`sort_key`)) {
        RegistryFindRegisteredModelRequestObject[['sort_key']] <-
          self$`sort_key`
      }

      RegistryFindRegisteredModelRequestObject
    },
    fromJSON = function(RegistryFindRegisteredModelRequestJson) {
      RegistryFindRegisteredModelRequestObject <- jsonlite::fromJSON(RegistryFindRegisteredModelRequestJson)
      if (!is.null(RegistryFindRegisteredModelRequestObject$`workspace_name`)) {
        self$`workspace_name` <- RegistryFindRegisteredModelRequestObject$`workspace_name`
      }
      if (!is.null(RegistryFindRegisteredModelRequestObject$`predicates`)) {
        self$`predicates` <- ApiClient$new()$deserializeObj(RegistryFindRegisteredModelRequestObject$`predicates`, "array[CommonKeyValueQuery]", loadNamespace("openapi"))
      }
      if (!is.null(RegistryFindRegisteredModelRequestObject$`pagination`)) {
        paginationObject <- VertacommonPagination$new()
        paginationObject$fromJSON(jsonlite::toJSON(RegistryFindRegisteredModelRequestObject$pagination, auto_unbox = TRUE, digits = NA))
        self$`pagination` <- paginationObject
      }
      if (!is.null(RegistryFindRegisteredModelRequestObject$`ascending`)) {
        self$`ascending` <- RegistryFindRegisteredModelRequestObject$`ascending`
      }
      if (!is.null(RegistryFindRegisteredModelRequestObject$`sort_key`)) {
        self$`sort_key` <- RegistryFindRegisteredModelRequestObject$`sort_key`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`workspace_name`)) {
        sprintf(
        '"workspace_name":
          "%s"
                ',
        self$`workspace_name`
        )},
        if (!is.null(self$`predicates`)) {
        sprintf(
        '"predicates":
        [%s]
',
        paste(sapply(self$`predicates`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`pagination`)) {
        sprintf(
        '"pagination":
        %s
        ',
        jsonlite::toJSON(self$`pagination`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`ascending`)) {
        sprintf(
        '"ascending":
          "%s"
                ',
        self$`ascending`
        )},
        if (!is.null(self$`sort_key`)) {
        sprintf(
        '"sort_key":
          "%s"
                ',
        self$`sort_key`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistryFindRegisteredModelRequestJson) {
      RegistryFindRegisteredModelRequestObject <- jsonlite::fromJSON(RegistryFindRegisteredModelRequestJson)
      self$`workspace_name` <- RegistryFindRegisteredModelRequestObject$`workspace_name`
      self$`predicates` <- ApiClient$new()$deserializeObj(RegistryFindRegisteredModelRequestObject$`predicates`, "array[CommonKeyValueQuery]", loadNamespace("openapi"))
      self$`pagination` <- VertacommonPagination$new()$fromJSON(jsonlite::toJSON(RegistryFindRegisteredModelRequestObject$pagination, auto_unbox = TRUE, digits = NA))
      self$`ascending` <- RegistryFindRegisteredModelRequestObject$`ascending`
      self$`sort_key` <- RegistryFindRegisteredModelRequestObject$`sort_key`
      self
    }
  )
)

