# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
#
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistryFindModelVersionRequest
#'
#' @description RegistryFindModelVersionRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  \link{RegistryRegisteredModelIdentification} [optional]
#'
#' @field predicates Filtering supported on
#' 1. version
#' 2. labels
#' 3. description
#' 4. model_source
#' 5. experiment_run_id
#' 6. status
#' 7. archived status list( \link{CommonKeyValueQuery} ) [optional]
#'
#' @field pagination  \link{VertacommonPagination} [optional]
#'
#' @field ascending  character [optional]
#'
#' @field sort_key  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistryFindModelVersionRequest <- R6::R6Class(
  'RegistryFindModelVersionRequest',
  public = list(
    `id` = NULL,
    `predicates` = NULL,
    `pagination` = NULL,
    `ascending` = NULL,
    `sort_key` = NULL,
    initialize = function(
        `id`=NULL, `predicates`=NULL, `pagination`=NULL, `ascending`=NULL, `sort_key`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(R6::is.R6(`id`))
        self$`id` <- `id`
      }
      if (!is.null(`predicates`)) {
        stopifnot(is.vector(`predicates`), length(`predicates`) != 0)
        sapply(`predicates`, function(x) stopifnot(R6::is.R6(x)))
        self$`predicates` <- `predicates`
      }
      if (!is.null(`pagination`)) {
        stopifnot(R6::is.R6(`pagination`))
        self$`pagination` <- `pagination`
      }
      if (!is.null(`ascending`)) {
        self$`ascending` <- `ascending`
      }
      if (!is.null(`sort_key`)) {
        stopifnot(is.character(`sort_key`), length(`sort_key`) == 1)
        self$`sort_key` <- `sort_key`
      }
    },
    toJSON = function() {
      RegistryFindModelVersionRequestObject <- list()
      if (!is.null(self$`id`)) {
        RegistryFindModelVersionRequestObject[['id']] <-
          self$`id`$toJSON()
      }
      if (!is.null(self$`predicates`)) {
        RegistryFindModelVersionRequestObject[['predicates']] <-
          lapply(self$`predicates`, function(x) x$toJSON())
      }
      if (!is.null(self$`pagination`)) {
        RegistryFindModelVersionRequestObject[['pagination']] <-
          self$`pagination`$toJSON()
      }
      if (!is.null(self$`ascending`)) {
        RegistryFindModelVersionRequestObject[['ascending']] <-
          self$`ascending`
      }
      if (!is.null(self$`sort_key`)) {
        RegistryFindModelVersionRequestObject[['sort_key']] <-
          self$`sort_key`
      }

      RegistryFindModelVersionRequestObject
    },
    fromJSON = function(RegistryFindModelVersionRequestJson) {
      RegistryFindModelVersionRequestObject <- jsonlite::fromJSON(RegistryFindModelVersionRequestJson)
      if (!is.null(RegistryFindModelVersionRequestObject$`id`)) {
        idObject <- RegistryRegisteredModelIdentification$new()
        idObject$fromJSON(jsonlite::toJSON(RegistryFindModelVersionRequestObject$id, auto_unbox = TRUE, digits = NA))
        self$`id` <- idObject
      }
      if (!is.null(RegistryFindModelVersionRequestObject$`predicates`)) {
        self$`predicates` <- ApiClient$new()$deserializeObj(RegistryFindModelVersionRequestObject$`predicates`, "array[CommonKeyValueQuery]", loadNamespace("openapi"))
      }
      if (!is.null(RegistryFindModelVersionRequestObject$`pagination`)) {
        paginationObject <- VertacommonPagination$new()
        paginationObject$fromJSON(jsonlite::toJSON(RegistryFindModelVersionRequestObject$pagination, auto_unbox = TRUE, digits = NA))
        self$`pagination` <- paginationObject
      }
      if (!is.null(RegistryFindModelVersionRequestObject$`ascending`)) {
        self$`ascending` <- RegistryFindModelVersionRequestObject$`ascending`
      }
      if (!is.null(RegistryFindModelVersionRequestObject$`sort_key`)) {
        self$`sort_key` <- RegistryFindModelVersionRequestObject$`sort_key`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
        %s
        ',
        jsonlite::toJSON(self$`id`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`predicates`)) {
        sprintf(
        '"predicates":
        [%s]
',
        paste(sapply(self$`predicates`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`pagination`)) {
        sprintf(
        '"pagination":
        %s
        ',
        jsonlite::toJSON(self$`pagination`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`ascending`)) {
        sprintf(
        '"ascending":
          "%s"
                ',
        self$`ascending`
        )},
        if (!is.null(self$`sort_key`)) {
        sprintf(
        '"sort_key":
          "%s"
                ',
        self$`sort_key`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistryFindModelVersionRequestJson) {
      RegistryFindModelVersionRequestObject <- jsonlite::fromJSON(RegistryFindModelVersionRequestJson)
      self$`id` <- RegistryRegisteredModelIdentification$new()$fromJSON(jsonlite::toJSON(RegistryFindModelVersionRequestObject$id, auto_unbox = TRUE, digits = NA))
      self$`predicates` <- ApiClient$new()$deserializeObj(RegistryFindModelVersionRequestObject$`predicates`, "array[CommonKeyValueQuery]", loadNamespace("openapi"))
      self$`pagination` <- VertacommonPagination$new()$fromJSON(jsonlite::toJSON(RegistryFindModelVersionRequestObject$pagination, auto_unbox = TRUE, digits = NA))
      self$`ascending` <- RegistryFindModelVersionRequestObject$`ascending`
      self$`sort_key` <- RegistryFindModelVersionRequestObject$`sort_key`
      self
    }
  )
)

