# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistryCommitMultipartArtifact
#'
#' @description RegistryCommitMultipartArtifact Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field model_version_id id of model version character [optional]
#'
#' @field key artifact key character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistryCommitMultipartArtifact <- R6::R6Class(
  'RegistryCommitMultipartArtifact',
  public = list(
    `model_version_id` = NULL,
    `key` = NULL,
    initialize = function(
        `model_version_id`=NULL, `key`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`model_version_id`)) {
        stopifnot(is.character(`model_version_id`), length(`model_version_id`) == 1)
        self$`model_version_id` <- `model_version_id`
      }
      if (!is.null(`key`)) {
        stopifnot(is.character(`key`), length(`key`) == 1)
        self$`key` <- `key`
      }
    },
    toJSON = function() {
      RegistryCommitMultipartArtifactObject <- list()
      if (!is.null(self$`model_version_id`)) {
        RegistryCommitMultipartArtifactObject[['model_version_id']] <-
          self$`model_version_id`
      }
      if (!is.null(self$`key`)) {
        RegistryCommitMultipartArtifactObject[['key']] <-
          self$`key`
      }

      RegistryCommitMultipartArtifactObject
    },
    fromJSON = function(RegistryCommitMultipartArtifactJson) {
      RegistryCommitMultipartArtifactObject <- jsonlite::fromJSON(RegistryCommitMultipartArtifactJson)
      if (!is.null(RegistryCommitMultipartArtifactObject$`model_version_id`)) {
        self$`model_version_id` <- RegistryCommitMultipartArtifactObject$`model_version_id`
      }
      if (!is.null(RegistryCommitMultipartArtifactObject$`key`)) {
        self$`key` <- RegistryCommitMultipartArtifactObject$`key`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`model_version_id`)) {
        sprintf(
        '"model_version_id":
          "%s"
                ',
        self$`model_version_id`
        )},
        if (!is.null(self$`key`)) {
        sprintf(
        '"key":
          "%s"
                ',
        self$`key`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistryCommitMultipartArtifactJson) {
      RegistryCommitMultipartArtifactObject <- jsonlite::fromJSON(RegistryCommitMultipartArtifactJson)
      self$`model_version_id` <- RegistryCommitMultipartArtifactObject$`model_version_id`
      self$`key` <- RegistryCommitMultipartArtifactObject$`key`
      self
    }
  )
)

