# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistryModelVersionIdentification
#'
#' @description RegistryModelVersionIdentification Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field model_version_id ModelVersion referred to by id character [optional]
#'
#' @field model_id  \link{RegistryRegisteredModelIdentification} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistryModelVersionIdentification <- R6::R6Class(
  'RegistryModelVersionIdentification',
  public = list(
    `model_version_id` = NULL,
    `model_id` = NULL,
    initialize = function(
        `model_version_id`=NULL, `model_id`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`model_version_id`)) {
        stopifnot(is.character(`model_version_id`), length(`model_version_id`) == 1)
        self$`model_version_id` <- `model_version_id`
      }
      if (!is.null(`model_id`)) {
        stopifnot(R6::is.R6(`model_id`))
        self$`model_id` <- `model_id`
      }
    },
    toJSON = function() {
      RegistryModelVersionIdentificationObject <- list()
      if (!is.null(self$`model_version_id`)) {
        RegistryModelVersionIdentificationObject[['model_version_id']] <-
          self$`model_version_id`
      }
      if (!is.null(self$`model_id`)) {
        RegistryModelVersionIdentificationObject[['model_id']] <-
          self$`model_id`$toJSON()
      }

      RegistryModelVersionIdentificationObject
    },
    fromJSON = function(RegistryModelVersionIdentificationJson) {
      RegistryModelVersionIdentificationObject <- jsonlite::fromJSON(RegistryModelVersionIdentificationJson)
      if (!is.null(RegistryModelVersionIdentificationObject$`model_version_id`)) {
        self$`model_version_id` <- RegistryModelVersionIdentificationObject$`model_version_id`
      }
      if (!is.null(RegistryModelVersionIdentificationObject$`model_id`)) {
        model_idObject <- RegistryRegisteredModelIdentification$new()
        model_idObject$fromJSON(jsonlite::toJSON(RegistryModelVersionIdentificationObject$model_id, auto_unbox = TRUE, digits = NA))
        self$`model_id` <- model_idObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`model_version_id`)) {
        sprintf(
        '"model_version_id":
          "%s"
                ',
        self$`model_version_id`
        )},
        if (!is.null(self$`model_id`)) {
        sprintf(
        '"model_id":
        %s
        ',
        jsonlite::toJSON(self$`model_id`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistryModelVersionIdentificationJson) {
      RegistryModelVersionIdentificationObject <- jsonlite::fromJSON(RegistryModelVersionIdentificationJson)
      self$`model_version_id` <- RegistryModelVersionIdentificationObject$`model_version_id`
      self$`model_id` <- RegistryRegisteredModelIdentification$new()$fromJSON(jsonlite::toJSON(RegistryModelVersionIdentificationObject$model_id, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

