# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistryModelVersion
#'
#' @description RegistryModelVersion Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id internal id character [optional]
#'
#' @field registered_model_id id of the model this belongs to character [optional]
#'
#' @field version Model&#39;s tag. Unique for a model nmae character [optional]
#'
#' @field time_updated  character [optional]
#'
#' @field time_created  character [optional]
#'
#' @field description  character [optional]
#'
#' @field experiment_run_id  character [optional]
#'
#' @field labels Labels added to the registered models list( character ) [optional]
#'
#' @field model  \link{CommonArtifact} [optional]
#'
#' @field environment  \link{VersioningEnvironmentBlob} [optional]
#'
#' @field artifacts Other artifacts list( \link{CommonArtifact} ) [optional]
#'
#' @field archived  \link{TernaryEnumTernary} [optional]
#'
#' @field readme_text readme character [optional]
#'
#' @field apis APIs list( character ) [optional]
#'
#' @field owner owner&#39;s verta_id character [optional]
#'
#' @field attributes Other attributes list( \link{CommonKeyValue} ) [optional]
#'
#' @field stage  \link{StageEnumStage} [optional]
#'
#' @field lock_level  \link{ModelVersionLockLevelEnumModelVersionLockLevel} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistryModelVersion <- R6::R6Class(
  'RegistryModelVersion',
  public = list(
    `id` = NULL,
    `registered_model_id` = NULL,
    `version` = NULL,
    `time_updated` = NULL,
    `time_created` = NULL,
    `description` = NULL,
    `experiment_run_id` = NULL,
    `labels` = NULL,
    `model` = NULL,
    `environment` = NULL,
    `artifacts` = NULL,
    `archived` = NULL,
    `readme_text` = NULL,
    `apis` = NULL,
    `owner` = NULL,
    `attributes` = NULL,
    `stage` = NULL,
    `lock_level` = NULL,
    initialize = function(
        `id`=NULL, `registered_model_id`=NULL, `version`=NULL, `time_updated`=NULL, `time_created`=NULL, `description`=NULL, `experiment_run_id`=NULL, `labels`=NULL, `model`=NULL, `environment`=NULL, `artifacts`=NULL, `archived`=NULL, `readme_text`=NULL, `apis`=NULL, `owner`=NULL, `attributes`=NULL, `stage`=NULL, `lock_level`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`registered_model_id`)) {
        stopifnot(is.character(`registered_model_id`), length(`registered_model_id`) == 1)
        self$`registered_model_id` <- `registered_model_id`
      }
      if (!is.null(`version`)) {
        stopifnot(is.character(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
      if (!is.null(`time_updated`)) {
        stopifnot(is.character(`time_updated`), length(`time_updated`) == 1)
        self$`time_updated` <- `time_updated`
      }
      if (!is.null(`time_created`)) {
        stopifnot(is.character(`time_created`), length(`time_created`) == 1)
        self$`time_created` <- `time_created`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`experiment_run_id`)) {
        stopifnot(is.character(`experiment_run_id`), length(`experiment_run_id`) == 1)
        self$`experiment_run_id` <- `experiment_run_id`
      }
      if (!is.null(`labels`)) {
        stopifnot(is.vector(`labels`), length(`labels`) != 0)
        sapply(`labels`, function(x) stopifnot(is.character(x)))
        self$`labels` <- `labels`
      }
      if (!is.null(`model`)) {
        stopifnot(R6::is.R6(`model`))
        self$`model` <- `model`
      }
      if (!is.null(`environment`)) {
        stopifnot(R6::is.R6(`environment`))
        self$`environment` <- `environment`
      }
      if (!is.null(`artifacts`)) {
        stopifnot(is.vector(`artifacts`), length(`artifacts`) != 0)
        sapply(`artifacts`, function(x) stopifnot(R6::is.R6(x)))
        self$`artifacts` <- `artifacts`
      }
      if (!is.null(`archived`)) {
        stopifnot(R6::is.R6(`archived`))
        self$`archived` <- `archived`
      }
      if (!is.null(`readme_text`)) {
        stopifnot(is.character(`readme_text`), length(`readme_text`) == 1)
        self$`readme_text` <- `readme_text`
      }
      if (!is.null(`apis`)) {
        stopifnot(is.vector(`apis`), length(`apis`) != 0)
        sapply(`apis`, function(x) stopifnot(is.character(x)))
        self$`apis` <- `apis`
      }
      if (!is.null(`owner`)) {
        stopifnot(is.character(`owner`), length(`owner`) == 1)
        self$`owner` <- `owner`
      }
      if (!is.null(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(R6::is.R6(x)))
        self$`attributes` <- `attributes`
      }
      if (!is.null(`stage`)) {
        stopifnot(R6::is.R6(`stage`))
        self$`stage` <- `stage`
      }
      if (!is.null(`lock_level`)) {
        stopifnot(R6::is.R6(`lock_level`))
        self$`lock_level` <- `lock_level`
      }
    },
    toJSON = function() {
      RegistryModelVersionObject <- list()
      if (!is.null(self$`id`)) {
        RegistryModelVersionObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`registered_model_id`)) {
        RegistryModelVersionObject[['registered_model_id']] <-
          self$`registered_model_id`
      }
      if (!is.null(self$`version`)) {
        RegistryModelVersionObject[['version']] <-
          self$`version`
      }
      if (!is.null(self$`time_updated`)) {
        RegistryModelVersionObject[['time_updated']] <-
          self$`time_updated`
      }
      if (!is.null(self$`time_created`)) {
        RegistryModelVersionObject[['time_created']] <-
          self$`time_created`
      }
      if (!is.null(self$`description`)) {
        RegistryModelVersionObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`experiment_run_id`)) {
        RegistryModelVersionObject[['experiment_run_id']] <-
          self$`experiment_run_id`
      }
      if (!is.null(self$`labels`)) {
        RegistryModelVersionObject[['labels']] <-
          self$`labels`
      }
      if (!is.null(self$`model`)) {
        RegistryModelVersionObject[['model']] <-
          self$`model`$toJSON()
      }
      if (!is.null(self$`environment`)) {
        RegistryModelVersionObject[['environment']] <-
          self$`environment`$toJSON()
      }
      if (!is.null(self$`artifacts`)) {
        RegistryModelVersionObject[['artifacts']] <-
          lapply(self$`artifacts`, function(x) x$toJSON())
      }
      if (!is.null(self$`archived`)) {
        RegistryModelVersionObject[['archived']] <-
          self$`archived`$toJSON()
      }
      if (!is.null(self$`readme_text`)) {
        RegistryModelVersionObject[['readme_text']] <-
          self$`readme_text`
      }
      if (!is.null(self$`apis`)) {
        RegistryModelVersionObject[['apis']] <-
          self$`apis`
      }
      if (!is.null(self$`owner`)) {
        RegistryModelVersionObject[['owner']] <-
          self$`owner`
      }
      if (!is.null(self$`attributes`)) {
        RegistryModelVersionObject[['attributes']] <-
          lapply(self$`attributes`, function(x) x$toJSON())
      }
      if (!is.null(self$`stage`)) {
        RegistryModelVersionObject[['stage']] <-
          self$`stage`$toJSON()
      }
      if (!is.null(self$`lock_level`)) {
        RegistryModelVersionObject[['lock_level']] <-
          self$`lock_level`$toJSON()
      }

      RegistryModelVersionObject
    },
    fromJSON = function(RegistryModelVersionJson) {
      RegistryModelVersionObject <- jsonlite::fromJSON(RegistryModelVersionJson)
      if (!is.null(RegistryModelVersionObject$`id`)) {
        self$`id` <- RegistryModelVersionObject$`id`
      }
      if (!is.null(RegistryModelVersionObject$`registered_model_id`)) {
        self$`registered_model_id` <- RegistryModelVersionObject$`registered_model_id`
      }
      if (!is.null(RegistryModelVersionObject$`version`)) {
        self$`version` <- RegistryModelVersionObject$`version`
      }
      if (!is.null(RegistryModelVersionObject$`time_updated`)) {
        self$`time_updated` <- RegistryModelVersionObject$`time_updated`
      }
      if (!is.null(RegistryModelVersionObject$`time_created`)) {
        self$`time_created` <- RegistryModelVersionObject$`time_created`
      }
      if (!is.null(RegistryModelVersionObject$`description`)) {
        self$`description` <- RegistryModelVersionObject$`description`
      }
      if (!is.null(RegistryModelVersionObject$`experiment_run_id`)) {
        self$`experiment_run_id` <- RegistryModelVersionObject$`experiment_run_id`
      }
      if (!is.null(RegistryModelVersionObject$`labels`)) {
        self$`labels` <- ApiClient$new()$deserializeObj(RegistryModelVersionObject$`labels`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(RegistryModelVersionObject$`model`)) {
        modelObject <- CommonArtifact$new()
        modelObject$fromJSON(jsonlite::toJSON(RegistryModelVersionObject$model, auto_unbox = TRUE, digits = NA))
        self$`model` <- modelObject
      }
      if (!is.null(RegistryModelVersionObject$`environment`)) {
        environmentObject <- VersioningEnvironmentBlob$new()
        environmentObject$fromJSON(jsonlite::toJSON(RegistryModelVersionObject$environment, auto_unbox = TRUE, digits = NA))
        self$`environment` <- environmentObject
      }
      if (!is.null(RegistryModelVersionObject$`artifacts`)) {
        self$`artifacts` <- ApiClient$new()$deserializeObj(RegistryModelVersionObject$`artifacts`, "array[CommonArtifact]", loadNamespace("openapi"))
      }
      if (!is.null(RegistryModelVersionObject$`archived`)) {
        archivedObject <- TernaryEnumTernary$new()
        archivedObject$fromJSON(jsonlite::toJSON(RegistryModelVersionObject$archived, auto_unbox = TRUE, digits = NA))
        self$`archived` <- archivedObject
      }
      if (!is.null(RegistryModelVersionObject$`readme_text`)) {
        self$`readme_text` <- RegistryModelVersionObject$`readme_text`
      }
      if (!is.null(RegistryModelVersionObject$`apis`)) {
        self$`apis` <- ApiClient$new()$deserializeObj(RegistryModelVersionObject$`apis`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(RegistryModelVersionObject$`owner`)) {
        self$`owner` <- RegistryModelVersionObject$`owner`
      }
      if (!is.null(RegistryModelVersionObject$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(RegistryModelVersionObject$`attributes`, "array[CommonKeyValue]", loadNamespace("openapi"))
      }
      if (!is.null(RegistryModelVersionObject$`stage`)) {
        stageObject <- StageEnumStage$new()
        stageObject$fromJSON(jsonlite::toJSON(RegistryModelVersionObject$stage, auto_unbox = TRUE, digits = NA))
        self$`stage` <- stageObject
      }
      if (!is.null(RegistryModelVersionObject$`lock_level`)) {
        lock_levelObject <- ModelVersionLockLevelEnumModelVersionLockLevel$new()
        lock_levelObject$fromJSON(jsonlite::toJSON(RegistryModelVersionObject$lock_level, auto_unbox = TRUE, digits = NA))
        self$`lock_level` <- lock_levelObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`registered_model_id`)) {
        sprintf(
        '"registered_model_id":
          "%s"
                ',
        self$`registered_model_id`
        )},
        if (!is.null(self$`version`)) {
        sprintf(
        '"version":
          "%s"
                ',
        self$`version`
        )},
        if (!is.null(self$`time_updated`)) {
        sprintf(
        '"time_updated":
          "%s"
                ',
        self$`time_updated`
        )},
        if (!is.null(self$`time_created`)) {
        sprintf(
        '"time_created":
          "%s"
                ',
        self$`time_created`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`experiment_run_id`)) {
        sprintf(
        '"experiment_run_id":
          "%s"
                ',
        self$`experiment_run_id`
        )},
        if (!is.null(self$`labels`)) {
        sprintf(
        '"labels":
           [%s]
        ',
        paste(unlist(lapply(self$`labels`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`model`)) {
        sprintf(
        '"model":
        %s
        ',
        jsonlite::toJSON(self$`model`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`environment`)) {
        sprintf(
        '"environment":
        %s
        ',
        jsonlite::toJSON(self$`environment`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`artifacts`)) {
        sprintf(
        '"artifacts":
        [%s]
',
        paste(sapply(self$`artifacts`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`archived`)) {
        sprintf(
        '"archived":
        %s
        ',
        jsonlite::toJSON(self$`archived`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`readme_text`)) {
        sprintf(
        '"readme_text":
          "%s"
                ',
        self$`readme_text`
        )},
        if (!is.null(self$`apis`)) {
        sprintf(
        '"apis":
           [%s]
        ',
        paste(unlist(lapply(self$`apis`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`owner`)) {
        sprintf(
        '"owner":
          "%s"
                ',
        self$`owner`
        )},
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
        [%s]
',
        paste(sapply(self$`attributes`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`stage`)) {
        sprintf(
        '"stage":
        %s
        ',
        jsonlite::toJSON(self$`stage`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`lock_level`)) {
        sprintf(
        '"lock_level":
        %s
        ',
        jsonlite::toJSON(self$`lock_level`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistryModelVersionJson) {
      RegistryModelVersionObject <- jsonlite::fromJSON(RegistryModelVersionJson)
      self$`id` <- RegistryModelVersionObject$`id`
      self$`registered_model_id` <- RegistryModelVersionObject$`registered_model_id`
      self$`version` <- RegistryModelVersionObject$`version`
      self$`time_updated` <- RegistryModelVersionObject$`time_updated`
      self$`time_created` <- RegistryModelVersionObject$`time_created`
      self$`description` <- RegistryModelVersionObject$`description`
      self$`experiment_run_id` <- RegistryModelVersionObject$`experiment_run_id`
      self$`labels` <- ApiClient$new()$deserializeObj(RegistryModelVersionObject$`labels`, "array[character]", loadNamespace("openapi"))
      self$`model` <- CommonArtifact$new()$fromJSON(jsonlite::toJSON(RegistryModelVersionObject$model, auto_unbox = TRUE, digits = NA))
      self$`environment` <- VersioningEnvironmentBlob$new()$fromJSON(jsonlite::toJSON(RegistryModelVersionObject$environment, auto_unbox = TRUE, digits = NA))
      self$`artifacts` <- ApiClient$new()$deserializeObj(RegistryModelVersionObject$`artifacts`, "array[CommonArtifact]", loadNamespace("openapi"))
      self$`archived` <- TernaryEnumTernary$new()$fromJSON(jsonlite::toJSON(RegistryModelVersionObject$archived, auto_unbox = TRUE, digits = NA))
      self$`readme_text` <- RegistryModelVersionObject$`readme_text`
      self$`apis` <- ApiClient$new()$deserializeObj(RegistryModelVersionObject$`apis`, "array[character]", loadNamespace("openapi"))
      self$`owner` <- RegistryModelVersionObject$`owner`
      self$`attributes` <- ApiClient$new()$deserializeObj(RegistryModelVersionObject$`attributes`, "array[CommonKeyValue]", loadNamespace("openapi"))
      self$`stage` <- StageEnumStage$new()$fromJSON(jsonlite::toJSON(RegistryModelVersionObject$stage, auto_unbox = TRUE, digits = NA))
      self$`lock_level` <- ModelVersionLockLevelEnumModelVersionLockLevel$new()$fromJSON(jsonlite::toJSON(RegistryModelVersionObject$lock_level, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

