# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistryFindRegisteredModelRequestResponse
#'
#' @description RegistryFindRegisteredModelRequestResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field registered_models  list( \link{RegistryRegisteredModel} ) [optional]
#'
#' @field total_records  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistryFindRegisteredModelRequestResponse <- R6::R6Class(
  'RegistryFindRegisteredModelRequestResponse',
  public = list(
    `registered_models` = NULL,
    `total_records` = NULL,
    initialize = function(
        `registered_models`=NULL, `total_records`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`registered_models`)) {
        stopifnot(is.vector(`registered_models`), length(`registered_models`) != 0)
        sapply(`registered_models`, function(x) stopifnot(R6::is.R6(x)))
        self$`registered_models` <- `registered_models`
      }
      if (!is.null(`total_records`)) {
        stopifnot(is.character(`total_records`), length(`total_records`) == 1)
        self$`total_records` <- `total_records`
      }
    },
    toJSON = function() {
      RegistryFindRegisteredModelRequestResponseObject <- list()
      if (!is.null(self$`registered_models`)) {
        RegistryFindRegisteredModelRequestResponseObject[['registered_models']] <-
          lapply(self$`registered_models`, function(x) x$toJSON())
      }
      if (!is.null(self$`total_records`)) {
        RegistryFindRegisteredModelRequestResponseObject[['total_records']] <-
          self$`total_records`
      }

      RegistryFindRegisteredModelRequestResponseObject
    },
    fromJSON = function(RegistryFindRegisteredModelRequestResponseJson) {
      RegistryFindRegisteredModelRequestResponseObject <- jsonlite::fromJSON(RegistryFindRegisteredModelRequestResponseJson)
      if (!is.null(RegistryFindRegisteredModelRequestResponseObject$`registered_models`)) {
        self$`registered_models` <- ApiClient$new()$deserializeObj(RegistryFindRegisteredModelRequestResponseObject$`registered_models`, "array[RegistryRegisteredModel]", loadNamespace("openapi"))
      }
      if (!is.null(RegistryFindRegisteredModelRequestResponseObject$`total_records`)) {
        self$`total_records` <- RegistryFindRegisteredModelRequestResponseObject$`total_records`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`registered_models`)) {
        sprintf(
        '"registered_models":
        [%s]
',
        paste(sapply(self$`registered_models`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`total_records`)) {
        sprintf(
        '"total_records":
          "%s"
                ',
        self$`total_records`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistryFindRegisteredModelRequestResponseJson) {
      RegistryFindRegisteredModelRequestResponseObject <- jsonlite::fromJSON(RegistryFindRegisteredModelRequestResponseJson)
      self$`registered_models` <- ApiClient$new()$deserializeObj(RegistryFindRegisteredModelRequestResponseObject$`registered_models`, "array[RegistryRegisteredModel]", loadNamespace("openapi"))
      self$`total_records` <- RegistryFindRegisteredModelRequestResponseObject$`total_records`
      self
    }
  )
)

