# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistryGetUrlForArtifactResponse
#'
#' @description RegistryGetUrlForArtifactResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field url URL based on action character [optional]
#'
#' @field multipart_upload_ok  character [optional]
#'
#' @field fields  named list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistryGetUrlForArtifactResponse <- R6::R6Class(
  'RegistryGetUrlForArtifactResponse',
  public = list(
    `url` = NULL,
    `multipart_upload_ok` = NULL,
    `fields` = NULL,
    initialize = function(
        `url`=NULL, `multipart_upload_ok`=NULL, `fields`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`url`)) {
        stopifnot(is.character(`url`), length(`url`) == 1)
        self$`url` <- `url`
      }
      if (!is.null(`multipart_upload_ok`)) {
        self$`multipart_upload_ok` <- `multipart_upload_ok`
      }
      if (!is.null(`fields`)) {
        stopifnot(is.vector(`fields`), length(`fields`) != 0)
        sapply(`fields`, function(x) stopifnot(is.character(x)))
        self$`fields` <- `fields`
      }
    },
    toJSON = function() {
      RegistryGetUrlForArtifactResponseObject <- list()
      if (!is.null(self$`url`)) {
        RegistryGetUrlForArtifactResponseObject[['url']] <-
          self$`url`
      }
      if (!is.null(self$`multipart_upload_ok`)) {
        RegistryGetUrlForArtifactResponseObject[['multipart_upload_ok']] <-
          self$`multipart_upload_ok`
      }
      if (!is.null(self$`fields`)) {
        RegistryGetUrlForArtifactResponseObject[['fields']] <-
          self$`fields`
      }

      RegistryGetUrlForArtifactResponseObject
    },
    fromJSON = function(RegistryGetUrlForArtifactResponseJson) {
      RegistryGetUrlForArtifactResponseObject <- jsonlite::fromJSON(RegistryGetUrlForArtifactResponseJson)
      if (!is.null(RegistryGetUrlForArtifactResponseObject$`url`)) {
        self$`url` <- RegistryGetUrlForArtifactResponseObject$`url`
      }
      if (!is.null(RegistryGetUrlForArtifactResponseObject$`multipart_upload_ok`)) {
        self$`multipart_upload_ok` <- RegistryGetUrlForArtifactResponseObject$`multipart_upload_ok`
      }
      if (!is.null(RegistryGetUrlForArtifactResponseObject$`fields`)) {
        self$`fields` <- ApiClient$new()$deserializeObj(RegistryGetUrlForArtifactResponseObject$`fields`, "map(character)", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`url`)) {
        sprintf(
        '"url":
          "%s"
                ',
        self$`url`
        )},
        if (!is.null(self$`multipart_upload_ok`)) {
        sprintf(
        '"multipart_upload_ok":
          "%s"
                ',
        self$`multipart_upload_ok`
        )},
        if (!is.null(self$`fields`)) {
        sprintf(
        '"fields":
          "%s"
        ',
        jsonlite::toJSON(lapply(self$`fields`, function(x){ x }), auto_unbox = TRUE, digits=NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistryGetUrlForArtifactResponseJson) {
      RegistryGetUrlForArtifactResponseObject <- jsonlite::fromJSON(RegistryGetUrlForArtifactResponseJson)
      self$`url` <- RegistryGetUrlForArtifactResponseObject$`url`
      self$`multipart_upload_ok` <- RegistryGetUrlForArtifactResponseObject$`multipart_upload_ok`
      self$`fields` <- ApiClient$new()$deserializeObj(RegistryGetUrlForArtifactResponseObject$`fields`, "map(character)", loadNamespace("openapi"))
      self
    }
  )
)

