# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RegistrySetModelVersion
#'
#' @description RegistrySetModelVersion Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  \link{RegistryModelVersionIdentification} [optional]
#'
#' @field model_version  \link{RegistryModelVersion} [optional]
#'
#' @field update_mask  \link{ProtobufFieldMask} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RegistrySetModelVersion <- R6::R6Class(
  'RegistrySetModelVersion',
  public = list(
    `id` = NULL,
    `model_version` = NULL,
    `update_mask` = NULL,
    initialize = function(
        `id`=NULL, `model_version`=NULL, `update_mask`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(R6::is.R6(`id`))
        self$`id` <- `id`
      }
      if (!is.null(`model_version`)) {
        stopifnot(R6::is.R6(`model_version`))
        self$`model_version` <- `model_version`
      }
      if (!is.null(`update_mask`)) {
        stopifnot(R6::is.R6(`update_mask`))
        self$`update_mask` <- `update_mask`
      }
    },
    toJSON = function() {
      RegistrySetModelVersionObject <- list()
      if (!is.null(self$`id`)) {
        RegistrySetModelVersionObject[['id']] <-
          self$`id`$toJSON()
      }
      if (!is.null(self$`model_version`)) {
        RegistrySetModelVersionObject[['model_version']] <-
          self$`model_version`$toJSON()
      }
      if (!is.null(self$`update_mask`)) {
        RegistrySetModelVersionObject[['update_mask']] <-
          self$`update_mask`$toJSON()
      }

      RegistrySetModelVersionObject
    },
    fromJSON = function(RegistrySetModelVersionJson) {
      RegistrySetModelVersionObject <- jsonlite::fromJSON(RegistrySetModelVersionJson)
      if (!is.null(RegistrySetModelVersionObject$`id`)) {
        idObject <- RegistryModelVersionIdentification$new()
        idObject$fromJSON(jsonlite::toJSON(RegistrySetModelVersionObject$id, auto_unbox = TRUE, digits = NA))
        self$`id` <- idObject
      }
      if (!is.null(RegistrySetModelVersionObject$`model_version`)) {
        model_versionObject <- RegistryModelVersion$new()
        model_versionObject$fromJSON(jsonlite::toJSON(RegistrySetModelVersionObject$model_version, auto_unbox = TRUE, digits = NA))
        self$`model_version` <- model_versionObject
      }
      if (!is.null(RegistrySetModelVersionObject$`update_mask`)) {
        update_maskObject <- ProtobufFieldMask$new()
        update_maskObject$fromJSON(jsonlite::toJSON(RegistrySetModelVersionObject$update_mask, auto_unbox = TRUE, digits = NA))
        self$`update_mask` <- update_maskObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
        %s
        ',
        jsonlite::toJSON(self$`id`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`model_version`)) {
        sprintf(
        '"model_version":
        %s
        ',
        jsonlite::toJSON(self$`model_version`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`update_mask`)) {
        sprintf(
        '"update_mask":
        %s
        ',
        jsonlite::toJSON(self$`update_mask`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RegistrySetModelVersionJson) {
      RegistrySetModelVersionObject <- jsonlite::fromJSON(RegistrySetModelVersionJson)
      self$`id` <- RegistryModelVersionIdentification$new()$fromJSON(jsonlite::toJSON(RegistrySetModelVersionObject$id, auto_unbox = TRUE, digits = NA))
      self$`model_version` <- RegistryModelVersion$new()$fromJSON(jsonlite::toJSON(RegistrySetModelVersionObject$model_version, auto_unbox = TRUE, digits = NA))
      self$`update_mask` <- ProtobufFieldMask$new()$fromJSON(jsonlite::toJSON(RegistrySetModelVersionObject$update_mask, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

