# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VersioningDockerEnvironmentBlob
#'
#' @description VersioningDockerEnvironmentBlob Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field repository  character [optional]
#'
#' @field tag  character [optional]
#'
#' @field sha  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VersioningDockerEnvironmentBlob <- R6::R6Class(
  'VersioningDockerEnvironmentBlob',
  public = list(
    `repository` = NULL,
    `tag` = NULL,
    `sha` = NULL,
    initialize = function(
        `repository`=NULL, `tag`=NULL, `sha`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`repository`)) {
        stopifnot(is.character(`repository`), length(`repository`) == 1)
        self$`repository` <- `repository`
      }
      if (!is.null(`tag`)) {
        stopifnot(is.character(`tag`), length(`tag`) == 1)
        self$`tag` <- `tag`
      }
      if (!is.null(`sha`)) {
        stopifnot(is.character(`sha`), length(`sha`) == 1)
        self$`sha` <- `sha`
      }
    },
    toJSON = function() {
      VersioningDockerEnvironmentBlobObject <- list()
      if (!is.null(self$`repository`)) {
        VersioningDockerEnvironmentBlobObject[['repository']] <-
          self$`repository`
      }
      if (!is.null(self$`tag`)) {
        VersioningDockerEnvironmentBlobObject[['tag']] <-
          self$`tag`
      }
      if (!is.null(self$`sha`)) {
        VersioningDockerEnvironmentBlobObject[['sha']] <-
          self$`sha`
      }

      VersioningDockerEnvironmentBlobObject
    },
    fromJSON = function(VersioningDockerEnvironmentBlobJson) {
      VersioningDockerEnvironmentBlobObject <- jsonlite::fromJSON(VersioningDockerEnvironmentBlobJson)
      if (!is.null(VersioningDockerEnvironmentBlobObject$`repository`)) {
        self$`repository` <- VersioningDockerEnvironmentBlobObject$`repository`
      }
      if (!is.null(VersioningDockerEnvironmentBlobObject$`tag`)) {
        self$`tag` <- VersioningDockerEnvironmentBlobObject$`tag`
      }
      if (!is.null(VersioningDockerEnvironmentBlobObject$`sha`)) {
        self$`sha` <- VersioningDockerEnvironmentBlobObject$`sha`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`repository`)) {
        sprintf(
        '"repository":
          "%s"
                ',
        self$`repository`
        )},
        if (!is.null(self$`tag`)) {
        sprintf(
        '"tag":
          "%s"
                ',
        self$`tag`
        )},
        if (!is.null(self$`sha`)) {
        sprintf(
        '"sha":
          "%s"
                ',
        self$`sha`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VersioningDockerEnvironmentBlobJson) {
      VersioningDockerEnvironmentBlobObject <- jsonlite::fromJSON(VersioningDockerEnvironmentBlobJson)
      self$`repository` <- VersioningDockerEnvironmentBlobObject$`repository`
      self$`tag` <- VersioningDockerEnvironmentBlobObject$`tag`
      self$`sha` <- VersioningDockerEnvironmentBlobObject$`sha`
      self
    }
  )
)

