# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VersioningPythonEnvironmentBlob
#'
#' @description VersioningPythonEnvironmentBlob Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field version  \link{VersioningVersionEnvironmentBlob} [optional]
#'
#' @field requirements  list( \link{VersioningPythonRequirementEnvironmentBlob} ) [optional]
#'
#' @field constraints  list( \link{VersioningPythonRequirementEnvironmentBlob} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VersioningPythonEnvironmentBlob <- R6::R6Class(
  'VersioningPythonEnvironmentBlob',
  public = list(
    `version` = NULL,
    `requirements` = NULL,
    `constraints` = NULL,
    initialize = function(
        `version`=NULL, `requirements`=NULL, `constraints`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`version`)) {
        stopifnot(R6::is.R6(`version`))
        self$`version` <- `version`
      }
      if (!is.null(`requirements`)) {
        stopifnot(is.vector(`requirements`), length(`requirements`) != 0)
        sapply(`requirements`, function(x) stopifnot(R6::is.R6(x)))
        self$`requirements` <- `requirements`
      }
      if (!is.null(`constraints`)) {
        stopifnot(is.vector(`constraints`), length(`constraints`) != 0)
        sapply(`constraints`, function(x) stopifnot(R6::is.R6(x)))
        self$`constraints` <- `constraints`
      }
    },
    toJSON = function() {
      VersioningPythonEnvironmentBlobObject <- list()
      if (!is.null(self$`version`)) {
        VersioningPythonEnvironmentBlobObject[['version']] <-
          self$`version`$toJSON()
      }
      if (!is.null(self$`requirements`)) {
        VersioningPythonEnvironmentBlobObject[['requirements']] <-
          lapply(self$`requirements`, function(x) x$toJSON())
      }
      if (!is.null(self$`constraints`)) {
        VersioningPythonEnvironmentBlobObject[['constraints']] <-
          lapply(self$`constraints`, function(x) x$toJSON())
      }

      VersioningPythonEnvironmentBlobObject
    },
    fromJSON = function(VersioningPythonEnvironmentBlobJson) {
      VersioningPythonEnvironmentBlobObject <- jsonlite::fromJSON(VersioningPythonEnvironmentBlobJson)
      if (!is.null(VersioningPythonEnvironmentBlobObject$`version`)) {
        versionObject <- VersioningVersionEnvironmentBlob$new()
        versionObject$fromJSON(jsonlite::toJSON(VersioningPythonEnvironmentBlobObject$version, auto_unbox = TRUE, digits = NA))
        self$`version` <- versionObject
      }
      if (!is.null(VersioningPythonEnvironmentBlobObject$`requirements`)) {
        self$`requirements` <- ApiClient$new()$deserializeObj(VersioningPythonEnvironmentBlobObject$`requirements`, "array[VersioningPythonRequirementEnvironmentBlob]", loadNamespace("openapi"))
      }
      if (!is.null(VersioningPythonEnvironmentBlobObject$`constraints`)) {
        self$`constraints` <- ApiClient$new()$deserializeObj(VersioningPythonEnvironmentBlobObject$`constraints`, "array[VersioningPythonRequirementEnvironmentBlob]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`version`)) {
        sprintf(
        '"version":
        %s
        ',
        jsonlite::toJSON(self$`version`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`requirements`)) {
        sprintf(
        '"requirements":
        [%s]
',
        paste(sapply(self$`requirements`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`constraints`)) {
        sprintf(
        '"constraints":
        [%s]
',
        paste(sapply(self$`constraints`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VersioningPythonEnvironmentBlobJson) {
      VersioningPythonEnvironmentBlobObject <- jsonlite::fromJSON(VersioningPythonEnvironmentBlobJson)
      self$`version` <- VersioningVersionEnvironmentBlob$new()$fromJSON(jsonlite::toJSON(VersioningPythonEnvironmentBlobObject$version, auto_unbox = TRUE, digits = NA))
      self$`requirements` <- ApiClient$new()$deserializeObj(VersioningPythonEnvironmentBlobObject$`requirements`, "array[VersioningPythonRequirementEnvironmentBlob]", loadNamespace("openapi"))
      self$`constraints` <- ApiClient$new()$deserializeObj(VersioningPythonEnvironmentBlobObject$`constraints`, "array[VersioningPythonRequirementEnvironmentBlob]", loadNamespace("openapi"))
      self
    }
  )
)

