# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VersioningPythonRequirementEnvironmentBlob
#'
#' @description VersioningPythonRequirementEnvironmentBlob Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field library  character [optional]
#'
#' @field constraint  character [optional]
#'
#' @field version  \link{VersioningVersionEnvironmentBlob} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VersioningPythonRequirementEnvironmentBlob <- R6::R6Class(
  'VersioningPythonRequirementEnvironmentBlob',
  public = list(
    `library` = NULL,
    `constraint` = NULL,
    `version` = NULL,
    initialize = function(
        `library`=NULL, `constraint`=NULL, `version`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`library`)) {
        stopifnot(is.character(`library`), length(`library`) == 1)
        self$`library` <- `library`
      }
      if (!is.null(`constraint`)) {
        stopifnot(is.character(`constraint`), length(`constraint`) == 1)
        self$`constraint` <- `constraint`
      }
      if (!is.null(`version`)) {
        stopifnot(R6::is.R6(`version`))
        self$`version` <- `version`
      }
    },
    toJSON = function() {
      VersioningPythonRequirementEnvironmentBlobObject <- list()
      if (!is.null(self$`library`)) {
        VersioningPythonRequirementEnvironmentBlobObject[['library']] <-
          self$`library`
      }
      if (!is.null(self$`constraint`)) {
        VersioningPythonRequirementEnvironmentBlobObject[['constraint']] <-
          self$`constraint`
      }
      if (!is.null(self$`version`)) {
        VersioningPythonRequirementEnvironmentBlobObject[['version']] <-
          self$`version`$toJSON()
      }

      VersioningPythonRequirementEnvironmentBlobObject
    },
    fromJSON = function(VersioningPythonRequirementEnvironmentBlobJson) {
      VersioningPythonRequirementEnvironmentBlobObject <- jsonlite::fromJSON(VersioningPythonRequirementEnvironmentBlobJson)
      if (!is.null(VersioningPythonRequirementEnvironmentBlobObject$`library`)) {
        self$`library` <- VersioningPythonRequirementEnvironmentBlobObject$`library`
      }
      if (!is.null(VersioningPythonRequirementEnvironmentBlobObject$`constraint`)) {
        self$`constraint` <- VersioningPythonRequirementEnvironmentBlobObject$`constraint`
      }
      if (!is.null(VersioningPythonRequirementEnvironmentBlobObject$`version`)) {
        versionObject <- VersioningVersionEnvironmentBlob$new()
        versionObject$fromJSON(jsonlite::toJSON(VersioningPythonRequirementEnvironmentBlobObject$version, auto_unbox = TRUE, digits = NA))
        self$`version` <- versionObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`library`)) {
        sprintf(
        '"library":
          "%s"
                ',
        self$`library`
        )},
        if (!is.null(self$`constraint`)) {
        sprintf(
        '"constraint":
          "%s"
                ',
        self$`constraint`
        )},
        if (!is.null(self$`version`)) {
        sprintf(
        '"version":
        %s
        ',
        jsonlite::toJSON(self$`version`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VersioningPythonRequirementEnvironmentBlobJson) {
      VersioningPythonRequirementEnvironmentBlobObject <- jsonlite::fromJSON(VersioningPythonRequirementEnvironmentBlobJson)
      self$`library` <- VersioningPythonRequirementEnvironmentBlobObject$`library`
      self$`constraint` <- VersioningPythonRequirementEnvironmentBlobObject$`constraint`
      self$`version` <- VersioningVersionEnvironmentBlob$new()$fromJSON(jsonlite::toJSON(VersioningPythonRequirementEnvironmentBlobObject$version, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

