# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VersioningEnvironmentBlob
#'
#' @description VersioningEnvironmentBlob Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field python  \link{VersioningPythonEnvironmentBlob} [optional]
#'
#' @field docker  \link{VersioningDockerEnvironmentBlob} [optional]
#'
#' @field environment_variables  list( \link{VersioningEnvironmentVariablesBlob} ) [optional]
#'
#' @field command_line  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VersioningEnvironmentBlob <- R6::R6Class(
  'VersioningEnvironmentBlob',
  public = list(
    `python` = NULL,
    `docker` = NULL,
    `environment_variables` = NULL,
    `command_line` = NULL,
    initialize = function(
        `python`=NULL, `docker`=NULL, `environment_variables`=NULL, `command_line`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`python`)) {
        stopifnot(R6::is.R6(`python`))
        self$`python` <- `python`
      }
      if (!is.null(`docker`)) {
        stopifnot(R6::is.R6(`docker`))
        self$`docker` <- `docker`
      }
      if (!is.null(`environment_variables`)) {
        stopifnot(is.vector(`environment_variables`), length(`environment_variables`) != 0)
        sapply(`environment_variables`, function(x) stopifnot(R6::is.R6(x)))
        self$`environment_variables` <- `environment_variables`
      }
      if (!is.null(`command_line`)) {
        stopifnot(is.vector(`command_line`), length(`command_line`) != 0)
        sapply(`command_line`, function(x) stopifnot(is.character(x)))
        self$`command_line` <- `command_line`
      }
    },
    toJSON = function() {
      VersioningEnvironmentBlobObject <- list()
      if (!is.null(self$`python`)) {
        VersioningEnvironmentBlobObject[['python']] <-
          self$`python`$toJSON()
      }
      if (!is.null(self$`docker`)) {
        VersioningEnvironmentBlobObject[['docker']] <-
          self$`docker`$toJSON()
      }
      if (!is.null(self$`environment_variables`)) {
        VersioningEnvironmentBlobObject[['environment_variables']] <-
          lapply(self$`environment_variables`, function(x) x$toJSON())
      }
      if (!is.null(self$`command_line`)) {
        VersioningEnvironmentBlobObject[['command_line']] <-
          self$`command_line`
      }

      VersioningEnvironmentBlobObject
    },
    fromJSON = function(VersioningEnvironmentBlobJson) {
      VersioningEnvironmentBlobObject <- jsonlite::fromJSON(VersioningEnvironmentBlobJson)
      if (!is.null(VersioningEnvironmentBlobObject$`python`)) {
        pythonObject <- VersioningPythonEnvironmentBlob$new()
        pythonObject$fromJSON(jsonlite::toJSON(VersioningEnvironmentBlobObject$python, auto_unbox = TRUE, digits = NA))
        self$`python` <- pythonObject
      }
      if (!is.null(VersioningEnvironmentBlobObject$`docker`)) {
        dockerObject <- VersioningDockerEnvironmentBlob$new()
        dockerObject$fromJSON(jsonlite::toJSON(VersioningEnvironmentBlobObject$docker, auto_unbox = TRUE, digits = NA))
        self$`docker` <- dockerObject
      }
      if (!is.null(VersioningEnvironmentBlobObject$`environment_variables`)) {
        self$`environment_variables` <- ApiClient$new()$deserializeObj(VersioningEnvironmentBlobObject$`environment_variables`, "array[VersioningEnvironmentVariablesBlob]", loadNamespace("openapi"))
      }
      if (!is.null(VersioningEnvironmentBlobObject$`command_line`)) {
        self$`command_line` <- ApiClient$new()$deserializeObj(VersioningEnvironmentBlobObject$`command_line`, "array[character]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`python`)) {
        sprintf(
        '"python":
        %s
        ',
        jsonlite::toJSON(self$`python`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`docker`)) {
        sprintf(
        '"docker":
        %s
        ',
        jsonlite::toJSON(self$`docker`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`environment_variables`)) {
        sprintf(
        '"environment_variables":
        [%s]
',
        paste(sapply(self$`environment_variables`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`command_line`)) {
        sprintf(
        '"command_line":
           [%s]
        ',
        paste(unlist(lapply(self$`command_line`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VersioningEnvironmentBlobJson) {
      VersioningEnvironmentBlobObject <- jsonlite::fromJSON(VersioningEnvironmentBlobJson)
      self$`python` <- VersioningPythonEnvironmentBlob$new()$fromJSON(jsonlite::toJSON(VersioningEnvironmentBlobObject$python, auto_unbox = TRUE, digits = NA))
      self$`docker` <- VersioningDockerEnvironmentBlob$new()$fromJSON(jsonlite::toJSON(VersioningEnvironmentBlobObject$docker, auto_unbox = TRUE, digits = NA))
      self$`environment_variables` <- ApiClient$new()$deserializeObj(VersioningEnvironmentBlobObject$`environment_variables`, "array[VersioningEnvironmentVariablesBlob]", loadNamespace("openapi"))
      self$`command_line` <- ApiClient$new()$deserializeObj(VersioningEnvironmentBlobObject$`command_line`, "array[character]", loadNamespace("openapi"))
      self
    }
  )
)

