# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VersioningVersionEnvironmentBlob
#'
#' @description VersioningVersionEnvironmentBlob Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field major  integer [optional]
#'
#' @field minor  integer [optional]
#'
#' @field patch  integer [optional]
#'
#' @field suffix  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VersioningVersionEnvironmentBlob <- R6::R6Class(
  'VersioningVersionEnvironmentBlob',
  public = list(
    `major` = NULL,
    `minor` = NULL,
    `patch` = NULL,
    `suffix` = NULL,
    initialize = function(
        `major`=NULL, `minor`=NULL, `patch`=NULL, `suffix`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`major`)) {
        stopifnot(is.numeric(`major`), length(`major`) == 1)
        self$`major` <- `major`
      }
      if (!is.null(`minor`)) {
        stopifnot(is.numeric(`minor`), length(`minor`) == 1)
        self$`minor` <- `minor`
      }
      if (!is.null(`patch`)) {
        stopifnot(is.numeric(`patch`), length(`patch`) == 1)
        self$`patch` <- `patch`
      }
      if (!is.null(`suffix`)) {
        stopifnot(is.character(`suffix`), length(`suffix`) == 1)
        self$`suffix` <- `suffix`
      }
    },
    toJSON = function() {
      VersioningVersionEnvironmentBlobObject <- list()
      if (!is.null(self$`major`)) {
        VersioningVersionEnvironmentBlobObject[['major']] <-
          self$`major`
      }
      if (!is.null(self$`minor`)) {
        VersioningVersionEnvironmentBlobObject[['minor']] <-
          self$`minor`
      }
      if (!is.null(self$`patch`)) {
        VersioningVersionEnvironmentBlobObject[['patch']] <-
          self$`patch`
      }
      if (!is.null(self$`suffix`)) {
        VersioningVersionEnvironmentBlobObject[['suffix']] <-
          self$`suffix`
      }

      VersioningVersionEnvironmentBlobObject
    },
    fromJSON = function(VersioningVersionEnvironmentBlobJson) {
      VersioningVersionEnvironmentBlobObject <- jsonlite::fromJSON(VersioningVersionEnvironmentBlobJson)
      if (!is.null(VersioningVersionEnvironmentBlobObject$`major`)) {
        self$`major` <- VersioningVersionEnvironmentBlobObject$`major`
      }
      if (!is.null(VersioningVersionEnvironmentBlobObject$`minor`)) {
        self$`minor` <- VersioningVersionEnvironmentBlobObject$`minor`
      }
      if (!is.null(VersioningVersionEnvironmentBlobObject$`patch`)) {
        self$`patch` <- VersioningVersionEnvironmentBlobObject$`patch`
      }
      if (!is.null(VersioningVersionEnvironmentBlobObject$`suffix`)) {
        self$`suffix` <- VersioningVersionEnvironmentBlobObject$`suffix`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`major`)) {
        sprintf(
        '"major":
          %d
                ',
        self$`major`
        )},
        if (!is.null(self$`minor`)) {
        sprintf(
        '"minor":
          %d
                ',
        self$`minor`
        )},
        if (!is.null(self$`patch`)) {
        sprintf(
        '"patch":
          %d
                ',
        self$`patch`
        )},
        if (!is.null(self$`suffix`)) {
        sprintf(
        '"suffix":
          "%s"
                ',
        self$`suffix`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VersioningVersionEnvironmentBlobJson) {
      VersioningVersionEnvironmentBlobObject <- jsonlite::fromJSON(VersioningVersionEnvironmentBlobJson)
      self$`major` <- VersioningVersionEnvironmentBlobObject$`major`
      self$`minor` <- VersioningVersionEnvironmentBlobObject$`minor`
      self$`patch` <- VersioningVersionEnvironmentBlobObject$`patch`
      self$`suffix` <- VersioningVersionEnvironmentBlobObject$`suffix`
      self
    }
  )
)

