# registry/RegistryService.proto
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: version not set
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VisibilityEnumVisibility
#'
#' @description VisibilityEnumVisibility Class
#'
#' @format An \code{R6Class} generator object
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VisibilityEnumVisibility <- R6::R6Class(
    "VisibilityEnumVisibility",
    public = list(
        initialize = function(...) {
            local.optional.var <- list(...)
            val <- unlist(local.optional.var)
            enumvec <- .parse_VisibilityEnumVisibility()

            stopifnot(length(val) == 1L)

            if (!val %in% enumvec)
                stop("Use one of the valid values: ",
                    paste0(enumvec, collapse = ", "))
            private$value <- val
        },
        toJSON = function() {
            jsonlite::toJSON(private$value, auto_unbox = TRUE)
        },
        fromJSON = function(VisibilityEnumVisibilityJson) {
            private$value <- jsonlite::fromJSON(VisibilityEnumVisibilityJson,
                simplifyVector = FALSE)
            self
        },
        toJSONString = function() {
            as.character(jsonlite::toJSON(private$value,
                auto_unbox = TRUE))
        },
        fromJSONString = function(VisibilityEnumVisibilityJson) {
            private$value <- jsonlite::fromJSON(VisibilityEnumVisibilityJson,
                simplifyVector = FALSE)
            self
        }
    ),
    private = list(
        value = NULL
    )
)

# add to utils.R
.parse_VisibilityEnumVisibility <- function(vals) {
    res <- gsub("^\\[|\\]$", "",
        "[PRIVATE, PUBLIC, ORG_SCOPED_PUBLIC, ORG_DEFAULT]"
    )
    unlist(strsplit(res, ", "))
}


